"""
Flow translations for 3 John — accurate, literal English renderings.
Every verse. Formal equivalence style. From the Greek New Testament (SBLGNT).
Jesus Christ IS the promised Messiah and King of everything.
Generated by generate_nt_flow.py using Claude Opus.
Verses: 15 | Notes: 7
"""

FLOW_3JOHN = {
    1: {  # Chapter 1
        1: 'The elder, to Gaius the beloved, whom I love in truth.',
        2: 'Beloved, concerning all things I pray that you prosper and be in health, even as your soul prospers.',
        3: 'For I rejoiced greatly when brothers came and bore witness to your truth, even as you walk in truth.',
        4: 'Greater joy than these things I have not, that I hear my children walking in the truth.',
        5: 'Beloved, you do a faithful thing in whatever you work toward the brothers, and this toward strangers,',
        6: 'who bore witness to your love before the assembly; whom you will do well to send forward in a manner worthy of God.',
        7: 'For on behalf of the Name they went out, receiving nothing from the Gentiles.',
        8: 'We therefore ought to support such ones, that we may become fellow workers with the truth.',
        9: 'I wrote something to the assembly, but Diotrephes, the one loving to have the preeminence among them, does not receive us.',
        10: 'Because of this, if I come, I will bring to remembrance his works which he does, prating against us with evil words; and not being content with these things, neither does he himself receive the brothers, and those desiring to do so he forbids, and casts them out of the assembly.',
        11: 'Beloved, do not imitate the evil, but the good. The one doing good is of God; the one doing evil has not seen God.',
        12: 'Testimony has been borne to Demetrius by all, and by the truth itself; and we also bear witness, and you know that our testimony is true.',
        13: 'Many things I had to write to you, but I do not wish through ink and reed-pen to write to you.',
        14: 'But I hope to see you shortly, and we shall speak mouth to mouth.',
        15: 'Peace to you. The friends greet you. Greet the friends by name.',
    },
}

NOTES_3JOHN = {
    1: {
        1: 'GREEK: "Presbuteros" (πρεσβύτερος, Strong\'s G4245) means "elder" and here serves as a self-designation of the apostle John, indicating both age and ecclesiastical authority. The term "en alētheia" (ἐν ἀληθείᾳ) can mean both "in truth" (i.e., truly/genuinely) and "in the Truth" as a reference to the gospel and the person of Christ (John 14:6). The identity of Gaius is debated; he is not certainly the same as Paul\'s Gaius in Romans 16:23 or 1 Corinthians 1:14.',
        4: 'GREEK: "Meizoterān" (μειζοτέραν) is a double comparative form — already comparative "meizōn" (greater) with an additional comparative suffix "-teros." This is a NT hapax legomenon in this precise form, intensifying the superlative sense: "no greater joy than this." THEOLOGICAL: The elder\'s supreme joy is located not in earthly prosperity but in faithful obedience to truth among his spiritual children, echoing the covenantal blessing pattern of walking in God\'s ways (Deut 5:33; Ps 86:11).',
        7: 'THEOLOGICAL: "The Name" (tou Onomatos, τοῦ Ὀνόματος) stands as an absolute reference to the name of Jesus Christ, recalling the OT pattern where "the Name" (ha-Shem) referred to YHWH Himself (Lev 24:11). These itinerant missionaries went out for Christ\'s sake and refused support from unbelieving Gentiles (ethnikōn, ἐθνικῶν, G1482), preserving the integrity of gospel witness. This establishes a pattern of Christian obligation to support gospel workers (cf. 1 Cor 9:14; Phil 4:15-16).',
        8: 'GREEK: "Hypolambanein" (ὑπολαμβάνειν, G5274) means "to take up, to support, to receive hospitably" — literally "to take from underneath," implying the bearing up of another\'s burden. "Synergoi" (συνεργοί, G4904) means "fellow workers" or "co-laborers," indicating that material support of missionaries constitutes genuine partnership in the work of truth itself.',
        9: 'GREEK: "Philoprōteuōn" (φιλοπρωτεύων, G5383) is a NT hapax legomenon meaning "loving to be first" or "desiring preeminence." It combines "philos" (loving) and "prōteuō" (to be first). HISTORICAL: Diotrephes appears to have seized unauthorized authority in a local assembly, rejecting apostolic emissaries and the elder\'s own letter. This represents an early instance of ecclesiastical power abuse, contrasting sharply with Christ\'s teaching on servant leadership (Mark 10:42-45).',
        11: 'THEOLOGICAL: This verse presents a foundational moral-theological principle: ethical conduct reveals spiritual origin. "The one doing good is of God" (ek tou theou estin) locates moral agency in divine begetting (cf. 1 John 2:29; 3:9-10). "Has not seen God" (ouch heōraken ton theon) does not refer to physical sight but to spiritual perception and intimate knowledge of God — the one who practices evil demonstrates no experiential knowledge of God whatsoever. This directly recalls 1 John 3:6.',
        15: 'GREEK: "Eirēnē soi" (Εἰρήνη σοι) reflects the Hebrew "shalom leka," the traditional covenantal greeting of peace (cf. Luke 24:36; John 20:19). "Tous philous kat\' onoma" (τοὺς φίλους κατ\' ὄνομα) — "the friends by name" — is striking; "philoi" (friends) as a designation for fellow believers recalls Jesus\' own words in John 15:15. The phrase "by name" echoes the Good Shepherd knowing His sheep individually (John 10:3).',
    },
}