"""
Flow translations for Nahum — accurate, literal English renderings.
Every verse of all chapters. Formal equivalence style.
YHWH = the divine name (tetragrammaton). Original translation from the Hebrew Masoretic Text.
Jesus Christ IS the promised Messiah and King of everything.
Generated by generate_ot_flow.py using Claude Sonnet.
Verses: 47 | Notes: 24
"""

FLOW_NAHUM = {
    1: {  # Chapter 1
        1: 'The burden (massa) of Nineveh. The book of the vision of Nahum the Elkoshite.',
        2: 'YHWH is a jealous and avenging God; YHWH is avenging and wrathful. YHWH takes vengeance on His adversaries and keeps wrath for His enemies.',
        3: 'YHWH is slow to anger and great in power, and YHWH will by no means clear the guilty. In whirlwind and in storm is His way, and the cloud is the dust of His feet.',
        4: 'He rebukes the sea and makes it dry, and He dries up all the rivers. Bashan and Carmel wither, and the blossom of Lebanon withers.',
        5: 'The mountains quake before Him, and the hills melt. The earth heaves before Him — the world and all who dwell in it.',
        6: 'Before His indignation who can stand? And who can endure the burning of His anger? His wrath is poured out like fire, and the rocks are broken in pieces by Him.',
        7: 'YHWH is good, a stronghold in the day of distress (tsarah); He knows those who take refuge in Him.',
        8: 'But with an overflowing flood He will make a complete end of her place, and darkness will pursue His enemies.',
        9: 'Whatever you plot against YHWH, He will make a complete end of it; distress will not rise up a second time.',
        10: 'For they are entangled like thorns, and they are drunk like drunkards; they are consumed like dry stubble fully dried.',
        11: 'From you has gone out one who plots evil against YHWH, a counselor of wickedness (belial).',
        12: 'Thus says YHWH: "Though they are at full strength and many, even so they will be cut down and pass away. Though I have afflicted you, I will afflict you no more."',
        13: '"And now I will break his yoke from upon you, and I will tear off your bonds."',
        14: 'And YHWH has commanded concerning you: "Your name shall be sown no more. From the house of your gods I will cut off the carved image and the metal image; I will make your grave, for you are vile."',
        15: 'Behold, upon the mountains the feet of him who brings good news, who proclaims shalom (shalom)! Keep your feasts, O Judah; fulfill your vows. For the wicked one (belial) will no more pass through you; he is utterly cut off.',
    },
    2: {  # Chapter 2
        1: 'The scatterer has come up against your face. Man the fortress, watch the road, strengthen your loins, fortify your power greatly.',
        2: 'For YHWH is restoring the majesty (ge\'on) of Jacob, as the majesty of Israel, for plunderers have plundered them and their vine branches they have ruined.',
        3: 'The shield of his mighty men is made red, the men of valor are clothed in scarlet; with fire of steel are the chariots in the day of his preparation, and the cypress spears are brandished.',
        4: 'Through the streets the chariots rage, they rush to and fro in the broad ways; their appearance is like torches, they dart about like the lightning flashes.',
        5: 'He calls his nobles — they stumble in their march; they hasten to her wall, and the siege engine is set up.',
        6: 'The gates of the rivers are opened, and the palace melts away.',
        7: 'It is decreed: she is stripped, she is carried away; and her maidservants are moaning as with the sound of doves, beating upon their breasts.',
        8: 'And Nineveh — she has been like a pool of water from her days of old, yet they are fleeing. "Stand! Stand!" — but none turns back.',
        9: 'Plunder silver, plunder gold! For there is no end to the treasure, an abundance of every precious thing.',
        10: 'Emptiness and void and devastation! And a melting heart, and knocking knees, and writhing in all loins, and the faces of all of them gather a glow of heat.',
        11: 'Where is the den of the lions, and the feeding place of the young lions, where the lion walked — the lioness, the lion\'s cub — and there was none who disturbed them?',
        12: 'The lion tore enough for his cubs, and strangled for his lionesses; and he filled his caves with prey, and his dens with torn flesh.',
        13: '\'Behold, I am against you,\' declares YHWH of hosts, \'and I will burn her chariots in smoke, and the sword shall devour your young lions, and I will cut off your prey from the earth, and the voice of your messengers shall no longer be heard.\'',
    },
    3: {  # Chapter 3
        1: 'Woe to the city of blood! All of it is full of lies and plunder; prey does not depart.',
        2: 'The crack of the whip, and the rumble of the wheel, and the galloping horse, and the bounding chariot!',
        3: 'The charging horseman and the flashing sword and the glittering spear, and a multitude of slain, and a mass of corpses — there is no end to the bodies; they stumble over their bodies.',
        4: 'Because of the multitude of the harlotries of the harlot, the charming one, the mistress of sorceries (kashaph), who sells nations through her harlotries and families through her sorceries —',
        5: '"Behold, I am against you," declares YHWH of hosts, "and I will lift up your skirts over your face, and I will show nations your nakedness and kingdoms your shame.',
        6: 'And I will throw abominations upon you and treat you with contempt and make you a spectacle.',
        7: 'And it shall come to pass that all who see you will flee from you and say, \'Nineveh is laid waste! Who will grieve for her?\' From where shall I seek comforters for you?"',
        8: 'Are you better than No-Amon that was situated by the rivers, with waters surrounding her, whose rampart was the sea, whose wall was from the sea?',
        9: 'Cush (Kush) was her strength, and Egypt, and there was no limit; Put and Lubim were among your helpers.',
        10: 'Yet even she became an exile; she went into captivity. Also her children were dashed to pieces at the head of every street; lots were cast over her honored men, and all her great men were bound in chains.',
        11: 'You also will be drunk; you will be hidden; you also will seek a refuge from the enemy.',
        12: 'All your fortresses are fig trees with first-ripe figs — if shaken, they fall into the mouth of the eater.',
        13: 'Behold, your people in your midst are women; the gates of your land are wide open to your enemies; fire has devoured your gate bars.',
        14: 'Draw water for the siege! Strengthen your fortresses! Go into the clay and tread the mortar! Take hold of the brick mold!',
        15: 'There fire will devour you; the sword will cut you off. It will devour you like the locust (arbeh). Multiply yourself like the locust; multiply yourself like the swarming locust!',
        16: 'You multiplied your merchants more than the stars of the heavens. The locust spreads its wings and flies away.',
        17: 'Your princes are like the swarming locust, and your scribes like swarms of locusts that settle on the walls on a cold day — the sun rises, and they flee away, and their place is not known; where they are is unknown.',
        18: 'Your shepherds slumber, O king of Assyria; your nobles lie down in rest. Your people are scattered on the mountains with none to gather them.',
        19: 'There is no assuaging of your hurt (shever); your wound (makkah) is grievous. All who hear the report of you clap their hands over you, for upon whom has not your evil passed continually?',
    },
}

NOTES_NAHUM = {
    1: {
        1: 'HEBREW: The term "massa" (Strong\'s H4853) means both "burden" and "oracle/utterance," carrying the sense of a weighty divine pronouncement. The name "Nahum" (H5151) means "comfort" or "consolation," an irony since comfort for Judah comes through devastating judgment on Nineveh. "Elkoshite" likely indicates a village of origin, though its location remains debated among scholars.',
        2: 'THEOLOGICAL: The threefold repetition of YHWH and the double use of "avenging" (naqam, H5358) establish the divine warrior\'s consuming zeal. The Hebrew "qanna" (jealous, H7067) is the same term used of YHWH in the Decalogue (Exod 20:5), linking covenant faithfulness to retributive justice. Divine vengeance here is not petty retaliation but the holy vindication of moral order.',
        3: 'THEOLOGICAL: The phrase "slow to anger" (erek appayim, H750+H639, lit. "long of nostrils") echoes the divine self-disclosure of Exod 34:6-7, yet here the emphasis falls on the trailing clause: He will not acquit the guilty. The theophanic imagery — whirlwind, storm, cloud — recalls Sinai and the divine warrior psalms (Ps 18:9-15), presenting YHWH as the sovereign of the storm.',
        4: 'DIVINE_COUNCIL: The withering of Bashan, Carmel, and Lebanon invokes regions associated with divine power and mythic fertility in the ancient Near East. Bashan was associated in Canaanite tradition with the realm of the dead and its ruling spirits (see Ps 68:15, 22; Deut 32:14). YHWH\'s rebuke of the sea (yam, H3220) echoes the ancient combat motif in which the storm deity conquers the sea — here subverted to proclaim YHWH\'s unchallenged supremacy over all cosmic forces.',
        7: 'THEOLOGICAL: Verse 7 forms the theological center of the acrostic hymn, pivoting from wrath to refuge. The phrase "knows those who take refuge in Him" uses the Hebrew "yada" (H3045), a term of intimate covenantal knowledge, not mere intellectual awareness. The "day of distress" (yom tsarah) is a technical phrase for eschatological crisis (Ps 50:15; Jer 15:11). This verse is closely echoed in Ps 46 and provides the basis for Paul\'s confidence in Rom 8:28-39.',
        11: 'THEOLOGICAL: The "counselor of wickedness" is rendered from the Hebrew "yo\'ets beliya\'al" — one who counsels worthlessness or destruction. "Belial" (H1100, beliya\'al) is a term of deep moral ruin, later personified as a demonic figure in Second Temple literature (2 Cor 6:15). This verse likely targets Sennacherib or his officials whose campaigns against Judah (701 BC) are in view.',
        14: 'HISTORICAL: The command to cut off "carved image and metal image" from the house of Nineveh\'s gods refers to the rich iconographic cult of Assyria, including the patron deity Ashur and Ishtar of Nineveh. Archaeological excavations at Nineveh (Kuyunjik) have confirmed the destruction of temple precincts and cultic objects. YHWH\'s declaration that He will make Nineveh\'s grave signals total dynastic extinction, fulfilled when the city fell to the Babylonian-Median coalition in 612 BC.',
        15: 'TYPOLOGY: The phrase "feet of him who brings good news" (mevaser, H1319) is cited verbatim in Isa 52:7 and applied by Paul to the proclamation of the gospel of Messiah in Rom 10:15. The word "shalom" here carries its full covenantal weight: wholeness, restoration, and the cessation of hostility. The call to keep feasts and fulfill vows signals the renewed liturgical life of a people freed from imperial oppression — a pattern fulfilled ultimately in the liberation wrought by Yeshua the Messiah.',
    },
    2: {
        1: 'HEBREW: The "scatterer" (mepiץ, H6327 root puץ) is a singular active participle, likely describing the Babylonian-Median coalition as YHWH\'s instrument of dispersion against Nineveh. The verse uses rapid-fire imperatives addressed to Nineveh, creating urgent military cadence. The irony is unmistakable — the empire that scattered nations now faces its own scatterer.',
        2: 'THEOLOGICAL: YHWH\'s act of judgment on Nineveh is simultaneously an act of covenantal restoration for Jacob and Israel. The term ge\'on (H1347, majesty or pride) typically carries negative connotations of arrogance, but here is used positively of the dignity YHWH restores to His people. This dual movement — enemy judged, people restored — is a hallmark of divine warrior theology throughout the Hebrew canon (cf. Deut 32:36, Isa 52:7).',
        3: 'HISTORICAL: The "fire of steel" or "flashing metal" on chariots likely refers to iron fittings or scythe-blades on Median and Babylonian war chariots attested in Neo-Babylonian records. The scarlet-clad warriors recall ANE reliefs depicting elite troops in dyed garments. The imagery previews the terrifying efficiency of YHWH\'s human instruments of judgment.',
        6: 'HISTORICAL: The "gates of the rivers" almost certainly references the Khosr River, which ran through Nineveh, whose sluice gates if breached would flood the city\'s defenses. Ancient sources, including Diodorus Siculus, describe exactly such a flooding event contributing to Nineveh\'s fall in 612 BC, giving this verse remarkable historical precision. This fulfillment confirms Nahum\'s prophetic authenticity.',
        10: 'HEBREW: Three near-synonymous terms — buqah (emptiness), umevuqah (void), umevullaqah (devastation) — form an alliterative tricolon (all beginning with mem or bet sounds in Hebrew) that mimics the collapsing sound of Nineveh itself. The cascading description of physical panic (melting heart, knocking knees, writhing loins, pale faces) echoes the covenant-curse language of Deuteronomy 28:65, applied here to an imperial oppressor.',
        11: 'DIVINE_COUNCIL: The lion imagery functions on two levels: historically as Assyria\'s own royal symbol (the lion hunt was the king\'s prerogative and lions adorned palace reliefs at Nineveh), and theologically as a reversal of dominion. YHWH, the true Lion of the divine council, strips the false imperial lion of its den. This anticipates the NT\'s contrast between the Lion of Judah (Rev 5:5) and the devouring lion adversary (1 Pet 5:8).',
        13: 'THEOLOGICAL: The formula "Behold, I am against you (hineni eleikh)" signals direct divine engagement in combat — YHWH Himself as the divine warrior takes the field. "YHWH of hosts" (YHWH Tseva\'ot, H6635) invokes the commander of heavenly armies. The burning of chariots recalls YHWH\'s earlier defeat of Egyptian war technology (Exod 15) and prefigures the eschatological destruction of all anti-God empire in Revelation 19:11-21.',
    },
    3: {
        1: 'HEBREW: "City of blood" (\'ir damim) is a concentrated accusation — damim (H1818, pl. of dam, "blood") implies both bloodshed and bloodguilt. The triple indictment of lies, plunder, and unceasing prey establishes the juridical basis for the woe oracle (hoy) that opens the verse. THEOLOGICAL: The "woe" (hoy, H1945) is a funeral lament inverted into judgment speech, pronouncing a death sentence upon Nineveh before it falls.',
        4: 'HEBREW: "Harlotries" (zenunim, from zanah, H2181) functions as a metaphor for imperial seduction — drawing nations into economic and political dependency through deception. "Sorceries" (keshaph, H3785) evokes genuine occult practice attested in Assyrian court religion, including incantation texts and omen divination. HISTORICAL: Assyrian royal ideology employed both military terror and religious propaganda to subjugate peoples, consistent with Nahum\'s language of enchantment and manipulation.',
        5: 'THEOLOGICAL: YHWH\'s declaration "I am against you" (hineni eleyikh, H2005 + H413) is the covenant lawsuit formula turned against a pagan oppressor — a rare but significant extension of divine judgment beyond Israel. The act of uncovering nakedness reverses the seductive exposure Nineveh inflicted on others, applying the principle of lex talionis at a national scale. DIVINE_COUNCIL: YHWH\'s title "of hosts" (tseva\'ot, H6635) invokes his role as commander of the heavenly armies, emphasizing that this is not merely political overthrow but cosmic warfare.',
        8: 'HISTORICAL: No-Amon (Hebrew: No\' Amon) is Thebes (Egyptian: Niwt-Imn, "City of Amon"), the great capital of Upper Egypt. Assyria itself sacked Thebes under Ashurbanipal in 663 BC, an event within living memory of Nahum\'s audience. The rhetorical question forces Nineveh to confront its own precedent: if Thebes with its divine patron and natural defenses fell, so too will you. THEOLOGICAL: The comparison implicitly demotes Amon, the Egyptian high god, and elevates YHWH as the one whose judgment no city can withstand.',
        9: 'HISTORICAL: Cush (Nubia/Ethiopia), Put (Libya), and Lubim (also Libyan peoples) represent the pan-African coalition that supported Thebes and the 25th (Cushite) Dynasty of Egypt. DIVINE_COUNCIL: The listing of national allies reflects the ANE theology of each nation having its patron deity — the fall of these coalitions implies the defeat of their divine patrons, consistent with Psalm 82 and Deuteronomy 32:8–9 theology.',
        13: 'THEOLOGICAL: The description of Nineveh\'s defenders as "women" is an ancient honor-shame inversion, not a comment on female capacity, but a declaration that Nineveh\'s warriors will be stripped of martial valor — a direct reversal of Assyria\'s celebrated military brutality. HISTORICAL: The burning of "gate bars" (beriach, H1280) refers to the destruction of the wooden or metal cross-bars securing city gates, a documented Assyrian siege tactic now turned against Nineveh itself.',
        15: 'HEBREW: "Locust" (arbeh, H697) appears twice in this verse, initiating an extended locust metaphor that runs through verse 17. The locust was a symbol of both overwhelming destructive invasion and sudden disappearance — both dimensions are exploited in Nahum\'s rhetoric. TYPOLOGY: The locust imagery anticipates Revelation 9\'s locust-army from the abyss, where similar language of consuming judgment is applied to eschatological warfare.',
        17: 'HEBREW: "Scribes" or "officials" (tipsar, H2951) is a loanword from Akkadian tupsar ("tablet writer" or "scribe"), reflecting Assyria\'s elaborate bureaucratic apparatus. The locust simile — warming on walls, then vanishing at sunrise — captures the unreliability of Nineveh\'s administrative class when the empire collapses. HISTORICAL: The fall of Nineveh in 612 BC confirmed Nahum\'s oracle precisely: the Assyrian administrative network evaporated with stunning speed once the capital fell.',
        19: 'HEBREW: "Hurt" or "fracture" (shever, H7667) implies not a surface wound but a shattering break — used elsewhere of catastrophic national ruin (Isa 30:26; Jer 6:14). "Wound" (makkah, H4347) is the blow or plague delivered by YHWH as divine warrior. THEOLOGICAL: The closing verse functions as both verdict and doxology — the clapping of hands by the nations is not mere mockery but a liturgical acknowledgment that YHWH\'s justice has prevailed over the archetypal oppressor. TYPOLOGY: The universal "all who hear" anticipates the eschatological rejoicing over Babylon\'s fall in Revelation 18:20, where heaven and apostles and prophets are called to rejoice over divine judgment upon empire.',
    },
}