"""
Flow translations for Philemon — accurate, literal English renderings.
Every verse. Formal equivalence style. From the Greek New Testament (SBLGNT).
Jesus Christ IS the promised Messiah and King of everything.
Generated by generate_nt_flow.py using Claude Opus.
Verses: 25 | Notes: 11
"""

FLOW_PHILEMON = {
    1: {  # Chapter 1
        1: 'Paul, a prisoner of Christ Jesus, and Timothy the brother, to Philemon the beloved and fellow-worker of ours,',
        2: 'and to Apphia the sister, and to Archippus our fellow-soldier, and to the assembly at your house:',
        3: 'Grace to you and peace from God our Father and the Lord Jesus Christ.',
        4: 'I give thanks to my God always, making mention of you in my prayers,',
        5: 'hearing of your love and the faith which you have toward the Lord Jesus and toward all the saints,',
        6: 'so that the fellowship of your faith may become effective in the knowledge of every good thing that is in us unto Christ.',
        7: 'For I had much joy and comfort over your love, because the inward parts of the saints have been refreshed through you, brother.',
        8: 'Therefore, though having much boldness in Christ to command you that which is fitting,',
        9: 'on account of love I rather appeal — being such a one as Paul the aged, and now also a prisoner of Christ Jesus —',
        10: 'I appeal to you concerning my child, whom I begot in my bonds, Onesimus,',
        11: 'the one formerly useless to you, but now useful both to you and to me,',
        12: 'whom I have sent back to you — him, that is, my very inward parts.',
        13: 'whom I myself was wishing to keep with me, that on your behalf he might minister to me in the bonds of the gospel;',
        14: 'but apart from your consent I wished to do nothing, so that your good deed might not be as by compulsion but according to willingness.',
        15: 'For perhaps for this reason he was separated for an hour, that you might have him back eternally,',
        16: 'no longer as a slave, but above a slave — a beloved brother, especially to me, and how much more to you, both in the flesh and in the Lord.',
        17: 'If then you hold me as a partner, receive him as me.',
        18: 'But if he has wronged you in anything or owes anything, charge this to my account.',
        19: 'I, Paul, have written with my own hand: I will repay — that I may not say to you that you owe to me even your own self besides.',
        20: 'Yes, brother, let me have profit from you in the Lord; refresh my inward parts in Christ.',
        21: 'Having confidence in your obedience, I have written to you, knowing that you will do even beyond what I say.',
        22: 'And at the same time also prepare for me a lodging, for I hope that through your prayers I shall be granted to you.',
        23: 'Epaphras, my fellow-prisoner in Christ Jesus, greets you,',
        24: 'as do Mark, Aristarchus, Demas, and Luke, my fellow-workers.',
        25: 'The grace of the Lord Jesus Christ be with your spirit.',
    },
}

NOTES_PHILEMON = {
    1: {
        1: 'GREEK: "Désmios" (δέσμιος, Strong\'s G1198) means "prisoner" or "one in bonds." Paul identifies himself not by his apostolic title but as a prisoner of Christ Jesus, framing the entire letter in terms of voluntary subjection. "Synergos" (συνεργός, G4904) — "fellow-worker" — establishes Philemon as an active partner in Paul\'s gospel ministry.',
        2: 'GREEK: "Systratiōtēs" (συστρατιώτης, G4961) — "fellow-soldier" — a military metaphor Paul uses only here and in Phil 2:25, indicating Archippus\'s active role in spiritual warfare. HISTORICAL: The "assembly at your house" (ekklēsia kat\' oikon) reflects the standard pattern of early Christian worship gathering in private homes before the construction of dedicated church buildings.',
        6: 'THEOLOGICAL: This verse is notoriously difficult to translate. "Koinōnia tēs pisteōs" (the fellowship/sharing of your faith) likely refers to the outward expression of Philemon\'s faith through generous partnership. "Energēs" (ἐνεργής, G1756) means "effective, operative, at work." Paul prays that Philemon\'s active faith-sharing would deepen in full knowledge (epignōsis, G1922 — a strengthened form of gnōsis) of every good thing directed toward Christ.',
        9: 'GREEK: "Presbýtēs" (πρεσβύτης, G4246) means "old man, aged one." Some scholars conjecture an original "presbeutēs" (ambassador), but manuscript evidence supports "aged." Paul layers three identities — the person he is (Paul), his condition (aged), and his circumstance (prisoner) — to appeal to Philemon\'s compassion rather than exert apostolic authority.',
        10: 'GREEK: "Egennēsa" (ἐγέννησα) — "I begot" — indicates Paul led Onesimus to faith while imprisoned, making Onesimus his spiritual child (teknon, G5043). HISTORICAL: Onesimus (Ὀνήσιμος, G3682) means "useful" or "profitable," a common slave name in the Greco-Roman world, setting up the wordplay in v. 11.',
        11: 'GREEK: A masterful wordplay: "achrēstos" (ἄχρηστος, G890, "useless") and "euchrēstos" (εὔχρηστος, G2173, "useful") may also carry a secondary pun on "Christos" — formerly "without Christ" (a-Christos), now "well in Christ" (eu-Christos). This rhetorical device would not have been lost on a Greek-speaking audience.',
        16: 'THEOLOGICAL: Paul does not explicitly demand manumission, but the theological logic is devastating to the institution of slavery: a slave who is "a beloved brother" both "in the flesh and in the Lord" can no longer be treated as mere property. The phrase "above a slave" (hyper doulon) radically redefines the social relationship. TYPOLOGY: The pattern of a worthless one becoming precious echoes the redemptive work of Christ who transforms those dead in sin into beloved children (Eph 2:1-7).',
        17: 'THEOLOGICAL: "Koinōnos" (κοινωνός, G2844) — "partner, sharer" — carries covenantal weight. Paul asks Philemon to receive Onesimus with the same honor he would extend to Paul himself. This mirrors the imputation logic of the gospel: receive him as you would receive me (cf. 2 Cor 5:21).',
        18: 'TYPOLOGY: Paul\'s offer — "charge this to my account" (elloга, ἐλλόγα, G1677, an accounting term) — is a profound picture of substitutionary atonement. As Christ took our debt upon himself, Paul voluntarily assumes Onesimus\'s debt before Philemon. The language of imputation here (ellogeo) is the same root Paul uses in Rom 5:13 regarding the reckoning of sin.',
        19: 'GREEK: "Egraya tē emē cheiri" — "I wrote with my own hand" — indicates Paul took the pen from his amanuensis to personally guarantee the debt, functioning as a legally binding promissory note (chirographon). THEOLOGICAL: The subtle reminder that Philemon owes Paul his very self (seauton moi prosopheileis) elegantly neutralizes the financial claim, embedding the request within a web of mutual spiritual obligation.',
        25: 'GREEK: "Pneumatos hymōn" — "your (plural) spirit" — the plural pronoun indicates that while the letter is addressed primarily to Philemon, the final benediction encompasses the entire house church. The shift from singular "you" throughout the appeal to plural "your" here makes the community witnesses and participants in the outcome. THEOLOGICAL: The closing mirrors the opening grace (v. 3), forming an inclusio that frames the entire letter within the grace of the Lord Jesus Christ.',
    },
}