"""
Auto-generated interlinear Hebrew-English data for Nahum.

Source: Open Scriptures Hebrew Bible (OSHB) — CC BY 4.0
        Strong's Hebrew Dictionary — CC BY 4.0

Generated by build_interlinear.py

Keys:  h = Hebrew text (with vowel points)
       t = transliteration
       s = Strong's number
       g = English gloss
       m = morphology
"""

INTERLINEAR_NAHUM = {
    1: {
        "verses": [
            {
                "num": 1,
                "words": [
                    {"h": "מַשָּׂ֖א", "s": "H4853", "g": "in/with a burden", "m": "noun common"},
                    {"h": "נִֽינְוֵ֑ה", "s": "H5210", "g": "Nineveh", "m": "noun"},
                    {"h": "סֵ֧פֶר", "s": "H5612", "g": "properly", "m": "noun common"},
                    {"h": "חֲז֛וֹן", "s": "H2377", "g": "a sight", "m": "noun common"},
                    {"h": "נַח֖וּם", "s": "H5151", "g": "Nachum", "m": "noun"},
                    {"h": "הָאֶלְקֹשִֽׁי", "s": "H512", "g": "the Elkoshite", "m": "particle + noun"},
                ]
            },
            {
                "num": 2,
                "words": [
                    {"h": "אֵ֣ל", "s": "H410", "g": "strength", "m": "noun common"},
                    {"h": "קַנּ֤וֹא", "s": "H7072", "g": "jealous or angry", "m": "adj"},
                    {"h": "וְנֹקֵם֙", "s": "H5358", "g": "and to grudge", "m": "conjunction + verb qal participle active"},
                    {"h": "יְהוָ֔ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "נֹקֵ֥ם", "s": "H5358", "g": "to grudge", "m": "verb qal participle active"},
                    {"h": "יְהוָ֖ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "וּבַ֣עַל", "s": "H1167", "g": "and a master", "m": "conjunction + noun common"},
                    {"h": "חֵמָ֑ה", "s": "H2534", "g": "heat", "m": "noun common"},
                    {"h": "נֹקֵ֤ם", "s": "H5358", "g": "to grudge", "m": "verb qal participle active"},
                    {"h": "יְהוָה֙", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "לְצָרָ֔יו", "s": "H6862", "g": "to/for + and narrow", "m": "preposition + noun common + suffix"},
                    {"h": "וְנוֹטֵ֥ר", "s": "H5201", "g": "and to guard", "m": "conjunction + verb qal participle active"},
                    {"h": "ה֖וּא", "s": "H1931", "g": "he", "m": "pronoun plur"},
                    {"h": "לְאֹיְבָֽיו", "s": "H341", "g": "to/for hating", "m": "preposition + verb qal participle active + suffix"},
                ]
            },
            {
                "num": 3,
                "words": [
                    {"h": "יְהֹוָ֗ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "אֶ֤רֶךְ", "s": "H750", "g": "long", "m": "adj"},
                    {"h": "אַפַּ֨יִם֙", "s": "H639", "g": "properly", "m": "noun common determined"},
                    {"h": "וגדול", "s": "H1419", "g": "and great", "m": "conjunction + a"},
                    {"h": "וּגְדָל", "s": "H1419", "g": "and great", "m": "conjunction + a"},
                    {"h": "כֹּ֔חַ", "s": "H3581", "g": "in/with vigor", "m": "noun common"},
                    {"h": "וְנַקֵּ֖ה", "s": "H5352", "g": "and to be clean", "m": "conjunction + verb piel infinitive absolute"},
                    {"h": "לֹ֣א", "s": "H3808", "g": "not", "m": "particle"},
                    {"h": "יְנַקֶּ֑ה", "s": "H5352", "g": "to be clean", "m": "verb piel imperfect 3rd masc sing"},
                    {"h": "יְהוָ֗ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "בְּסוּפָ֤ה", "s": "H5492", "g": "in/with a hurricane", "m": "preposition + noun common"},
                    {"h": "וּבִשְׂעָרָה֙", "s": "H8183", "g": "and + in/with a hurricane", "m": "conjunction + preposition + noun common"},
                    {"h": "דַּרְכּ֔וֹ", "s": "H1870", "g": "a road", "m": "noun common + suffix"},
                    {"h": "וְעָנָ֖ן", "s": "H6051", "g": "and a cloud", "m": "conjunction + noun common"},
                    {"h": "אֲבַ֥ק", "s": "H80", "g": "light particles", "m": "noun common"},
                    {"h": "רַגְלָֽיו", "s": "H7272", "g": "a foot", "m": "noun common determined + suffix"},
                ]
            },
            {
                "num": 4,
                "words": [
                    {"h": "גּוֹעֵ֤ר", "s": "H1605", "g": "to chide", "m": "verb qal participle active"},
                    {"h": "בַּיָּם֙", "s": "H3220", "g": "in/with a sea or large body of water", "m": "preposition + noun common"},
                    {"h": "וַֽיַּבְּשֵׁ֔הוּ", "s": "H3001", "g": "and to be ashamed", "m": "conjunction + verb piel sequential imperfect 3rd masc sing + suffix"},
                    {"h": "וְכָל", "s": "H3605", "g": "and properly", "m": "conjunction + noun common"},
                    {"h": "הַנְּהָר֖וֹת", "s": "H5104", "g": "the a stream (including the sea", "m": "particle + noun common"},
                    {"h": "הֶֽחֱרִ֑יב", "s": "H2717", "g": "to parch i.e. to desolate", "m": "verb hiphil perfect 3rd masc sing"},
                    {"h": "אֻמְלַ֤ל", "s": "H535", "g": "to droop", "m": "verb pulal perfect 3rd masc sing"},
                    {"h": "בָּשָׁן֙", "s": "H1316", "g": "Bashan", "m": "noun"},
                    {"h": "וְכַרְמֶ֔ל", "s": "H3760", "g": "and Karmel", "m": "conjunction + noun"},
                    {"h": "וּפֶ֥רַח", "s": "H6525", "g": "and a calyx", "m": "conjunction + noun common"},
                    {"h": "לְבָנ֖וֹן", "s": "H3844", "g": "Lebanon", "m": "noun"},
                    {"h": "אֻמְלָֽל", "s": "H535", "g": "to droop", "m": "verb pulal perfect 3rd masc sing"},
                ]
            },
            {
                "num": 5,
                "words": [
                    {"h": "הָרִים֙", "s": "H2022", "g": "a mountain or range of hills", "m": "noun common"},
                    {"h": "רָעֲשׁ֣וּ", "s": "H7493", "g": "to undulate (as the earth", "m": "verb qal perfect 3rd common plur"},
                    {"h": "מִמֶּ֔נּוּ", "s": "H4480", "g": "properly", "m": "preposition + suffix"},
                    {"h": "וְהַגְּבָע֖וֹת", "s": "H1389", "g": "and + the a hillock", "m": "conjunction + particle + noun common"},
                    {"h": "הִתְמֹגָ֑גוּ", "s": "H4127", "g": "to melt", "m": "verb hithpolel perfect 3rd common plur"},
                    {"h": "וַתִּשָּׂ֤א", "s": "H5375", "g": "and to lift", "m": "conjunction + verb qal sequential imperfect 3rd fem sing"},
                    {"h": "הָאָ֨רֶץ֙", "s": "H776", "g": "the the earth", "m": "particle + noun common"},
                    {"h": "מִפָּנָ֔יו", "s": "H6440", "g": "from the face", "m": "preposition + noun common + suffix"},
                    {"h": "וְתֵבֵ֖ל", "s": "H8398", "g": "and the earth", "m": "conjunction + noun common"},
                    {"h": "וְכָל", "s": "H3605", "g": "and properly", "m": "conjunction + noun common"},
                    {"h": "יֹ֥שְׁבֵי", "s": "H3427", "g": "properly", "m": "verb qal participle active"},
                    {"h": "בָֽהּ", "g": "in/with", "m": "preposition + suffix"},
                ]
            },
            {
                "num": 6,
                "words": [
                    {"h": "לִפְנֵ֤י", "s": "H6440", "g": "to/for the face", "m": "preposition + noun common"},
                    {"h": "זַעְמוֹ֙", "s": "H2195", "g": "strictly froth at the mouth", "m": "noun common + suffix"},
                    {"h": "מִ֣י", "s": "H4310", "g": "who?", "m": "particle"},
                    {"h": "יַֽעֲמ֔וֹד", "s": "H5975", "g": "to stand", "m": "verb qal imperfect 3rd masc sing"},
                    {"h": "וּמִ֥י", "s": "H4310", "g": "and who?", "m": "conjunction + particle"},
                    {"h": "יָק֖וּם", "s": "H6965", "g": "in/with to rise", "m": "verb qal imperfect 3rd masc sing"},
                    {"h": "בַּחֲר֣וֹן", "s": "H2740", "g": "in/with a burning of anger", "m": "preposition + noun common"},
                    {"h": "אַפּ֑וֹ", "s": "H639", "g": "properly", "m": "noun common + suffix"},
                    {"h": "חֲמָתוֹ֙", "s": "H2534", "g": "heat", "m": "noun common + suffix"},
                    {"h": "נִתְּכָ֣ה", "s": "H5413", "g": "to flow forth", "m": "verb niphal perfect 3rd fem sing"},
                    {"h": "כָאֵ֔שׁ", "s": "H784", "g": "as/like fire", "m": "preposition + noun common"},
                    {"h": "וְהַצֻּרִ֖ים", "s": "H6697", "g": "and + the properly", "m": "conjunction + particle + noun common"},
                    {"h": "נִתְּצ֥וּ", "s": "H5422", "g": "to tear down", "m": "verb niphal perfect 3rd common plur"},
                    {"h": "מִמֶּֽנּוּ", "s": "H4480", "g": "properly", "m": "preposition + suffix"},
                ]
            },
            {
                "num": 7,
                "words": [
                    {"h": "ט֣וֹב", "s": "H2896", "g": "good in the widest sense", "m": "adj"},
                    {"h": "יְהוָ֔ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "לְמָע֖וֹז", "s": "H4581", "g": "to/for a fortified place", "m": "preposition + noun common"},
                    {"h": "בְּי֣וֹם", "s": "H3117", "g": "in/with a day", "m": "preposition + noun common"},
                    {"h": "צָרָ֑ה", "s": "H6869", "g": "in/with tightness", "m": "noun common"},
                    {"h": "וְיֹדֵ֖עַ", "s": "H3045", "g": "and to know", "m": "conjunction + verb qal participle active"},
                    {"h": "חֹ֥סֵי", "s": "H2620", "g": "to flee for protection", "m": "verb qal participle active"},
                    {"h": "בֽוֹ", "g": "in/with", "m": "preposition + suffix"},
                ]
            },
            {
                "num": 8,
                "words": [
                    {"h": "וּבְשֶׁ֣טֶף", "s": "H7858", "g": "and + in/with a deluge", "m": "conjunction + preposition + noun common"},
                    {"h": "עֹבֵ֔ר", "s": "H5674", "g": "to cross over", "m": "verb qal participle active"},
                    {"h": "כָּלָ֖ה", "s": "H3617", "g": "a completion", "m": "noun common"},
                    {"h": "יַעֲשֶׂ֣ה", "s": "H6213", "g": "to do or make", "m": "verb qal imperfect 3rd masc sing"},
                    {"h": "מְקוֹמָ֑הּ", "s": "H4725", "g": "properly", "m": "noun common + suffix"},
                    {"h": "וְאֹיְבָ֖יו", "s": "H341", "g": "and hating", "m": "conjunction + verb qal participle active + suffix"},
                    {"h": "יְרַדֶּף", "s": "H7291", "g": "chase", "m": "verb piel imperfect 3rd masc sing"},
                    {"h": "חֹֽשֶׁךְ", "s": "H2822", "g": "the dark", "m": "noun common"},
                ]
            },
            {
                "num": 9,
                "words": [
                    {"h": "מַה", "s": "H4100", "g": "properly", "m": "particle"},
                    {"h": "תְּחַשְּׁבוּן֙", "s": "H2803", "g": "properly", "m": "verb piel imperfect 2nd masc plur + suffix"},
                    {"h": "אֶל", "s": "H413", "g": "near", "m": "preposition"},
                    {"h": "יְהוָ֔ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "כָּלָ֖ה", "s": "H3617", "g": "a completion", "m": "noun common"},
                    {"h": "ה֣וּא", "s": "H1931", "g": "he", "m": "pronoun plur"},
                    {"h": "עֹשֶׂ֑ה", "s": "H6213", "g": "to do or make", "m": "verb qal participle active"},
                    {"h": "לֹֽא", "s": "H3808", "g": "not", "m": "particle"},
                    {"h": "תָק֥וּם", "s": "H6965", "g": "in/with to rise", "m": "verb qal imperfect 3rd fem sing"},
                    {"h": "פַּעֲמַ֖יִם", "s": "H6471", "g": "a stroke", "m": "noun common determined"},
                    {"h": "צָרָֽה", "s": "H6869", "g": "in/with tightness", "m": "noun common"},
                ]
            },
            {
                "num": 10,
                "words": [
                    {"h": "כִּ֚י", "s": "H3588", "g": "and", "m": "conjunction"},
                    {"h": "עַד", "s": "H5704", "g": "as far as", "m": "preposition"},
                    {"h": "סִירִ֣ים", "s": "H5518", "g": "in/with a pot", "m": "noun common"},
                    {"h": "סְבֻכִ֔ים", "s": "H5440", "g": "to entwine", "m": "verb qal participle passive"},
                    {"h": "וּכְסָבְאָ֖ם", "s": "H5435", "g": "and + as/like potation", "m": "conjunction + preposition + noun common + suffix"},
                    {"h": "סְבוּאִ֑ים", "s": "H5433", "g": "to quaff to satiety", "m": "verb qal participle passive"},
                    {"h": "אֻ֨כְּל֔וּ", "s": "H398", "g": "to eat", "m": "verb qal passive perfect 3rd common plur"},
                    {"h": "כְּקַ֥שׁ", "s": "H7179", "g": "as/like straw", "m": "preposition + noun common"},
                    {"h": "יָבֵ֖שׁ", "s": "H3002", "g": "dry", "m": "adj"},
                    {"h": "מָלֵֽא", "s": "H4392", "g": "full or filling", "m": "adj"},
                ]
            },
            {
                "num": 11,
                "words": [
                    {"h": "מִמֵּ֣ךְ", "s": "H4480", "g": "properly", "m": "preposition + suffix"},
                    {"h": "יָצָ֔א", "s": "H3318", "g": "to go out", "m": "verb qal perfect 3rd masc sing"},
                    {"h": "חֹשֵׁ֥ב", "s": "H2803", "g": "properly", "m": "verb qal participle active"},
                    {"h": "עַל", "s": "H5921", "g": "above", "m": "preposition"},
                    {"h": "יְהוָ֖ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "רָעָ֑ה", "s": "H7451", "g": "and bad or evil", "m": "noun common"},
                    {"h": "יֹעֵ֖ץ", "s": "H3289", "g": "to advise", "m": "verb qal participle active"},
                    {"h": "בְּלִיָּֽעַל", "s": "H1100", "g": "without profit", "m": "noun common"},
                ]
            },
            {
                "num": 12,
                "words": [
                    {"h": "כֹּ֣ה", "s": "H3541", "g": "properly", "m": "adverb"},
                    {"h": "אָמַ֣ר", "s": "H559", "g": "to say", "m": "verb qal perfect 3rd masc sing"},
                    {"h": "יְהוָ֗ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "אִם", "s": "H518", "g": "(and", "m": "conjunction"},
                    {"h": "שְׁלֵמִים֙", "s": "H8003", "g": "complete", "m": "adj"},
                    {"h": "וְכֵ֣ן", "s": "H3651", "g": "and + and properly", "m": "conjunction + particle"},
                    {"h": "רַבִּ֔ים", "s": "H7227", "g": "abundant", "m": "adj"},
                    {"h": "וְכֵ֥ן", "s": "H3651", "g": "and + and properly", "m": "conjunction + particle"},
                    {"h": "נָגֹ֖זּוּ", "s": "H1494", "g": "to cut off", "m": "verb niphal perfect 3rd common plur"},
                    {"h": "וְעָבָ֑ר", "s": "H5674", "g": "and to cross over", "m": "conjunction + verb qal perfect 3rd masc sing"},
                    {"h": "וְעִ֨נִּתִ֔ךְ", "s": "H6031", "g": "and + in/with abase self", "m": "conjunction + verb piel perfect 1st common sing + suffix"},
                    {"h": "לֹ֥א", "s": "H3808", "g": "not", "m": "particle"},
                    {"h": "אֲעַנֵּ֖ךְ", "s": "H6031", "g": "in/with abase self", "m": "verb piel imperfect 1st common sing + suffix"},
                    {"h": "עֽוֹד", "s": "H5750", "g": "properly", "m": "adverb"},
                ]
            },
            {
                "num": 13,
                "words": [
                    {"h": "וְעַתָּ֕ה", "s": "H6258", "g": "and at this time", "m": "conjunction + adverb"},
                    {"h": "אֶשְׁבֹּ֥ר", "s": "H7665", "g": "to burst", "m": "verb qal imperfect 1st common sing"},
                    {"h": "מֹטֵ֖הוּ", "s": "H4132", "g": "a wavering", "m": "noun common + suffix"},
                    {"h": "מֵֽעָלָ֑יִךְ", "s": "H5921", "g": "from above", "m": "preposition + preposition + suffix"},
                    {"h": "וּמוֹסְרֹתַ֖יִךְ", "s": "H4147", "g": "and properly", "m": "conjunction + noun common + suffix"},
                    {"h": "אֲנַתֵּֽק", "s": "H5423", "g": "to tear off", "m": "verb piel imperfect 1st common sing"},
                ]
            },
            {
                "num": 14,
                "words": [
                    {"h": "וְצִוָּ֤ה", "s": "H6680", "g": "and to constitute", "m": "conjunction + verb piel perfect 3rd masc sing"},
                    {"h": "עָלֶ֨יךָ֙", "s": "H5921", "g": "above", "m": "preposition + suffix"},
                    {"h": "יְהוָ֔ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "לֹֽא", "s": "H3808", "g": "not", "m": "particle"},
                    {"h": "יִזָּרַ֥ע", "s": "H2232", "g": "to sow", "m": "verb niphal imperfect 3rd masc sing"},
                    {"h": "מִשִּׁמְךָ֖", "s": "H8034", "g": "from an appellation", "m": "preposition + noun common + suffix"},
                    {"h": "ע֑וֹד", "s": "H5750", "g": "properly", "m": "adverb"},
                    {"h": "מִבֵּ֨ית", "s": "H1004", "g": "from + in/with a house", "m": "preposition + noun common"},
                    {"h": "אֱלֹהֶ֜יךָ", "s": "H430", "g": "gods in the ordinary sense", "m": "noun common + suffix"},
                    {"h": "אַכְרִ֨ית", "s": "H3772", "g": "to cut", "m": "verb hiphil imperfect 1st common sing"},
                    {"h": "פֶּ֧סֶל", "s": "H6459", "g": "an idol", "m": "noun common"},
                    {"h": "וּמַסֵּכָ֛ה", "s": "H4541", "g": "and properly", "m": "conjunction + noun common"},
                    {"h": "אָשִׂ֥ים", "s": "H7760", "g": "to put", "m": "verb qal imperfect 1st common sing"},
                    {"h": "קִבְרֶ֖ךָ", "s": "H6913", "g": "a sepulchre", "m": "noun common + suffix"},
                    {"h": "כִּ֥י", "s": "H3588", "g": "and", "m": "conjunction"},
                    {"h": "קַלּֽוֹתָ", "s": "H7043", "g": "to be light", "m": "verb qal perfect 2nd masc sing"},
                ]
            },
        ]
    },
    2: {
        "verses": [
            {
                "num": 1,
                "words": [
                    {"h": "הִנֵּ֨ה", "s": "H2009", "g": "lo!", "m": "particle"},
                    {"h": "עַל", "s": "H5921", "g": "above", "m": "preposition"},
                    {"h": "הֶהָרִ֜ים", "s": "H2022", "g": "the a mountain or range of hills", "m": "particle + noun common"},
                    {"h": "רַגְלֵ֤י", "s": "H7272", "g": "a foot", "m": "noun common determined"},
                    {"h": "מְבַשֵּׂר֙", "s": "H1319", "g": "properly", "m": "verb piel participle active"},
                    {"h": "מַשְׁמִ֣יעַ", "s": "H8085", "g": "attentively", "m": "verb hiphil participle active"},
                    {"h": "שָׁל֔וֹם", "s": "H7965", "g": "safe", "m": "noun common"},
                    {"h": "חָגִּ֧י", "s": "H2287", "g": "properly", "m": "verb qal imperative 2nd fem sing"},
                    {"h": "יְהוּדָ֛ה", "s": "H3063", "g": "Jehudah", "m": "noun"},
                    {"h": "חַגַּ֖יִךְ", "s": "H2282", "g": "a festival", "m": "noun common + suffix"},
                    {"h": "שַׁלְּמִ֣י", "s": "H7999", "g": "to be safe", "m": "verb piel imperative 2nd fem sing"},
                    {"h": "נְדָרָ֑יִךְ", "s": "H5088", "g": "a promise", "m": "noun common + suffix"},
                    {"h": "כִּי֩", "s": "H3588", "g": "and", "m": "conjunction"},
                    {"h": "לֹ֨א", "s": "H3808", "g": "not", "m": "particle"},
                    {"h": "יוֹסִ֥יף", "s": "H3254", "g": "to add or augment", "m": "verb hiphil imperfect 3rd masc sing"},
                    {"h": "ע֛וֹד", "s": "H5750", "g": "properly", "m": "adverb"},
                    {"h": "לעבור", "s": "H5674", "g": "to/for to cross over", "m": "preposition + verb qal infinitive construct"},
                    {"h": "לַֽעֲבָר", "s": "H5674", "g": "to/for to cross over", "m": "preposition + verb qal infinitive construct"},
                    {"h": "בָּ֥ךְ", "g": "in/with", "m": "preposition + suffix"},
                    {"h": "בְּלִיַּ֖עַל", "s": "H1100", "g": "without profit", "m": "noun common"},
                    {"h": "כֻּלֹּ֥ה", "s": "H3605", "g": "properly", "m": "noun common + suffix"},
                    {"h": "נִכְרָֽת", "s": "H3772", "g": "to cut", "m": "verb niphal perfect 3rd masc sing"},
                ]
            },
            {
                "num": 2,
                "words": [
                    {"h": "עָלָ֥ה", "s": "H5927", "g": "to ascend", "m": "verb qal perfect 3rd masc sing"},
                    {"h": "מֵפִ֛יץ", "s": "H6327", "g": "in/with to dash in pieces", "m": "verb hiphil participle active"},
                    {"h": "עַל", "s": "H5921", "g": "above", "m": "preposition"},
                    {"h": "פָּנַ֖יִךְ", "s": "H6440", "g": "the face", "m": "noun common + suffix"},
                    {"h": "נָצ֣וֹר", "s": "H5341", "g": "to guard", "m": "verb qal infinitive absolute"},
                    {"h": "מְצֻרָ֑ה", "s": "H4694", "g": "a hemming in", "m": "noun common"},
                    {"h": "צַפֵּה", "s": "H6822", "g": "properly", "m": "verb piel imperative 2nd masc sing"},
                    {"h": "דֶ֨רֶךְ֙", "s": "H1870", "g": "a road", "m": "noun common"},
                    {"h": "חַזֵּ֣ק", "s": "H2388", "g": "to fasten upon", "m": "verb piel imperative 2nd masc sing"},
                    {"h": "מָתְנַ֔יִם", "s": "H4975", "g": "properly", "m": "noun common determined"},
                    {"h": "אַמֵּ֥ץ", "s": "H553", "g": "to be alert", "m": "verb piel imperative 2nd masc sing"},
                    {"h": "כֹּ֖חַ", "s": "H3581", "g": "in/with vigor", "m": "noun common"},
                    {"h": "מְאֹֽד", "s": "H3966", "g": "properly", "m": "adverb"},
                ]
            },
            {
                "num": 3,
                "words": [
                    {"h": "כִּ֣י", "s": "H3588", "g": "and", "m": "conjunction"},
                    {"h": "שָׁ֤ב", "s": "H7725", "g": "((break", "m": "verb qal perfect 3rd masc sing"},
                    {"h": "יְהוָה֙", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "אֶת", "s": "H853", "g": "properly", "m": "particle"},
                    {"h": "גְּא֣וֹן", "s": "H1347", "g": "{arrogance or majesty", "m": "noun common"},
                    {"h": "יַעֲקֹ֔ב", "s": "H3290", "g": "Jaakob", "m": "noun"},
                    {"h": "כִּגְא֖וֹן", "s": "H1347", "g": "as/like {arrogance or majesty", "m": "preposition + noun common"},
                    {"h": "יִשְׂרָאֵ֑ל", "s": "H3478", "g": "Jisrael", "m": "noun"},
                    {"h": "כִּ֤י", "s": "H3588", "g": "and", "m": "conjunction"},
                    {"h": "בְקָקוּם֙", "s": "H1238", "g": "in/with to pour out", "m": "verb qal perfect 3rd common plur + suffix"},
                    {"h": "בֹּֽקְקִ֔ים", "s": "H1238", "g": "in/with to pour out", "m": "verb qal participle active"},
                    {"h": "וּזְמֹרֵיהֶ֖ם", "s": "H2156", "g": "and a twig", "m": "conjunction + noun common + suffix"},
                    {"h": "שִׁחֵֽתוּ", "s": "H7843", "g": "to decay", "m": "verb piel perfect 3rd common plur"},
                ]
            },
            {
                "num": 4,
                "words": [
                    {"h": "מָגֵ֨ן", "s": "H4043", "g": "a shield", "m": "noun common"},
                    {"h": "גִּבֹּרֵ֜יהוּ", "s": "H1368", "g": "powerful", "m": "adj + suffix"},
                    {"h": "מְאָדָּ֗ם", "s": "H119", "g": "flush or turn rosy", "m": "verb pual participle passive"},
                    {"h": "אַנְשֵׁי", "s": "H376", "g": "also", "m": "noun common"},
                    {"h": "חַ֨יִל֙", "s": "H2428", "g": "probably a force", "m": "noun common"},
                    {"h": "מְתֻלָּעִ֔ים", "s": "H8529", "g": "to crimson", "m": "verb pual participle passive"},
                    {"h": "בְּאֵשׁ", "s": "H784", "g": "in/with fire", "m": "preposition + noun common"},
                    {"h": "פְּלָד֥וֹת", "s": "H6393", "g": "a cleaver", "m": "noun common"},
                    {"h": "הָרֶ֖כֶב", "s": "H7393", "g": "the a vehicle", "m": "particle + noun common"},
                    {"h": "בְּי֣וֹם", "s": "H3117", "g": "in/with a day", "m": "preposition + noun common"},
                    {"h": "הֲכִינ֑וֹ", "s": "H3559", "g": "properly", "m": "verb hiphil infinitive construct + suffix"},
                    {"h": "וְהַבְּרֹשִׁ֖ים", "s": "H1265", "g": "and + the a cypress tree", "m": "conjunction + particle + noun common"},
                    {"h": "הָרְעָֽלוּ", "s": "H7477", "g": "to reel", "m": "verb hophal perfect 3rd common plur"},
                ]
            },
            {
                "num": 5,
                "words": [
                    {"h": "בַּֽחוּצוֹת֙", "s": "H2351", "g": "in/with properly", "m": "preposition + noun common"},
                    {"h": "יִתְהוֹלְל֣וּ", "s": "H1984", "g": "in/with to be clear", "m": "verb hithpolel imperfect 3rd masc plur"},
                    {"h": "הָרֶ֔כֶב", "s": "H7393", "g": "the a vehicle", "m": "particle + noun common"},
                    {"h": "יִֽשְׁתַּקְשְׁק֖וּן", "s": "H8264", "g": "to course", "m": "verb hithpalpel imperfect 3rd masc plur + suffix"},
                    {"h": "בָּרְחֹב֑וֹת", "s": "H7339", "g": "in/with a width", "m": "preposition + noun common"},
                    {"h": "מַרְאֵיהֶן֙", "s": "H4758", "g": "a view", "m": "noun common + suffix"},
                    {"h": "כַּלַּפִּידִ֔ם", "s": "H3940", "g": "as/like a flambeau", "m": "preposition + noun common"},
                    {"h": "כַּבְּרָקִ֖ים", "s": "H1300", "g": "as/like + in/with lightning", "m": "preposition + noun common"},
                    {"h": "יְרוֹצֵֽצוּ", "s": "H7323", "g": "to run", "m": "verb polel imperfect 3rd masc plur"},
                ]
            },
            {
                "num": 6,
                "words": [
                    {"h": "יִזְכֹּר֙", "s": "H2142", "g": "properly", "m": "verb qal imperfect 3rd masc sing"},
                    {"h": "אַדִּירָ֔יו", "s": "H117", "g": "wide or large", "m": "adj + suffix"},
                    {"h": "יִכָּשְׁל֖וּ", "s": "H3782", "g": "to totter or waver", "m": "verb niphal imperfect 3rd masc plur"},
                    {"h": "בהלכותם", "s": "H1979", "g": "in/with a walking", "m": "preposition + noun common + suffix"},
                    {"h": "בַּהֲלִֽיכָתָ֑ם", "s": "H1979", "g": "in/with a walking", "m": "preposition + noun common + suffix"},
                    {"h": "יְמַֽהֲרוּ֙", "s": "H4116", "g": "properly", "m": "verb piel imperfect 3rd masc plur"},
                    {"h": "חֽוֹמָתָ֔הּ", "s": "H2346", "g": "a wall of protection", "m": "noun common + suffix"},
                    {"h": "וְהֻכַ֖ן", "s": "H3559", "g": "and properly", "m": "conjunction + verb hophal perfect 3rd masc sing"},
                    {"h": "הַסֹּכֵֽךְ", "s": "H5526", "g": "the + the properly", "m": "particle + noun common"},
                ]
            },
            {
                "num": 7,
                "words": [
                    {"h": "שַׁעֲרֵ֥י", "s": "H8179", "g": "an opening", "m": "noun common"},
                    {"h": "הַנְּהָר֖וֹת", "s": "H5104", "g": "the a stream (including the sea", "m": "particle + noun common"},
                    {"h": "נִפְתָּ֑חוּ", "s": "H6605", "g": "to open wide", "m": "verb niphal perfect 3rd common plur"},
                    {"h": "וְהַֽהֵיכָ֖ל", "s": "H1964", "g": "and + the a large public building", "m": "conjunction + particle + noun common"},
                    {"h": "נָמֽוֹג", "s": "H4127", "g": "to melt", "m": "verb niphal perfect 3rd masc sing"},
                ]
            },
            {
                "num": 8,
                "words": [
                    {"h": "וְהֻצַּ֖ב", "s": "H5324", "g": "and to station", "m": "conjunction + verb hophal perfect 3rd masc sing"},
                    {"h": "גֻּלְּתָ֣ה", "s": "H1540", "g": "to denude", "m": "verb pual perfect 3rd fem sing"},
                    {"h": "הֹֽעֲלָ֑תָה", "s": "H5927", "g": "to ascend", "m": "verb hophal perfect 3rd fem sing"},
                    {"h": "וְאַמְהֹתֶ֗יהָ", "s": "H519", "g": "and a maidservant or female slave", "m": "conjunction + noun common + suffix"},
                    {"h": "מְנַֽהֲגוֹת֙", "s": "H5090", "g": "in/with to drive forth", "m": "verb piel participle active"},
                    {"h": "כְּק֣וֹל", "s": "H6963", "g": "as/like a voice or sound", "m": "preposition + noun common"},
                    {"h": "יוֹנִ֔ים", "s": "H3123", "g": "a dove", "m": "noun common"},
                    {"h": "מְתֹפְפֹ֖ת", "s": "H8608", "g": "to drum", "m": "verb poel participle active"},
                    {"h": "עַל", "s": "H5921", "g": "above", "m": "preposition"},
                    {"h": "לִבְבֵהֶֽן", "s": "H3824", "g": "the heart", "m": "noun common + suffix"},
                ]
            },
            {
                "num": 9,
                "words": [
                    {"h": "וְנִינְוֵ֥ה", "s": "H5210", "g": "and Nineveh", "m": "conjunction + noun"},
                    {"h": "כִבְרֵֽכַת", "s": "H1295", "g": "as/like a reservoir", "m": "preposition + noun common"},
                    {"h": "מַ֖יִם", "s": "H4325", "g": "water", "m": "noun common"},
                    {"h": "מִ֣ימֵי", "s": "H3117", "g": "from a day", "m": "preposition + noun common"},
                    {"h": "הִ֑יא", "s": "H1931", "g": "he", "m": "pronoun plur"},
                    {"h": "וְהֵ֣מָּה", "s": "H1992", "g": "and they", "m": "conjunction + pronoun plur"},
                    {"h": "נָסִ֔ים", "s": "H5127", "g": "to flit", "m": "verb qal participle active"},
                    {"h": "עִמְד֥וּ", "s": "H5975", "g": "to stand", "m": "verb qal imperative 2nd masc plur"},
                    {"h": "עֲמֹ֖דוּ", "s": "H5975", "g": "to stand", "m": "verb qal imperative 2nd masc plur"},
                    {"h": "וְאֵ֥ין", "s": "H369", "g": "and a non-entity", "m": "conjunction + particle"},
                    {"h": "מַפְנֶֽה", "s": "H6437", "g": "to turn", "m": "verb hiphil participle active"},
                ]
            },
            {
                "num": 10,
                "words": [
                    {"h": "בֹּ֥זּוּ", "s": "H962", "g": "to plunder", "m": "verb qal imperative 2nd masc plur"},
                    {"h": "כֶ֖סֶף", "s": "H3701", "g": "silver", "m": "noun common"},
                    {"h": "בֹּ֣זּוּ", "s": "H962", "g": "to plunder", "m": "verb qal imperative 2nd masc plur"},
                    {"h": "זָהָ֑ב", "s": "H2091", "g": "gold", "m": "noun common"},
                    {"h": "וְאֵ֥ין", "s": "H369", "g": "and a non-entity", "m": "conjunction + particle"},
                    {"h": "קֵ֨צֶה֙", "s": "H7097", "g": "in/with an extremity", "m": "noun common"},
                    {"h": "לַתְּכוּנָ֔ה", "s": "H8498", "g": "to/for adjustment", "m": "preposition + noun common"},
                    {"h": "כָּבֹ֕ד", "s": "H3519", "g": "properly", "m": "noun common"},
                    {"h": "מִכֹּ֖ל", "s": "H3605", "g": "from properly", "m": "preposition + noun common"},
                    {"h": "כְּלִ֥י", "s": "H3627", "g": "something prepared", "m": "noun common"},
                    {"h": "חֶמְדָּֽה", "s": "H2532", "g": "delight", "m": "noun common"},
                ]
            },
            {
                "num": 11,
                "words": [
                    {"h": "בּוּקָ֥ה", "s": "H950", "g": "emptiness", "m": "noun common"},
                    {"h": "וּמְבוּקָ֖ה", "s": "H4003", "g": "and emptiness", "m": "conjunction + noun common"},
                    {"h": "וּמְבֻלָּקָ֑ה", "s": "H1110", "g": "and to annihilate", "m": "conjunction + verb pual participle passive"},
                    {"h": "וְלֵ֨ב", "s": "H3820", "g": "and the heart", "m": "conjunction + noun common"},
                    {"h": "נָמֵ֜ס", "s": "H4549", "g": "to liquefy", "m": "verb niphal perfect 3rd masc sing"},
                    {"h": "וּפִ֣ק", "s": "H6375", "g": "and a tottering", "m": "conjunction + noun common"},
                    {"h": "בִּרְכַּ֗יִם", "s": "H1290", "g": "a knee", "m": "noun common determined"},
                    {"h": "וְחַלְחָלָה֙", "s": "H2479", "g": "and writhing", "m": "conjunction + noun common"},
                    {"h": "בְּכָל", "s": "H3605", "g": "in/with properly", "m": "preposition + noun common"},
                    {"h": "מָתְנַ֔יִם", "s": "H4975", "g": "properly", "m": "noun common determined"},
                    {"h": "וּפְנֵ֥י", "s": "H6440", "g": "and the face", "m": "conjunction + noun common"},
                    {"h": "כֻלָּ֖ם", "s": "H3605", "g": "properly", "m": "noun common + suffix"},
                    {"h": "קִבְּצ֥וּ", "s": "H6908", "g": "to grasp", "m": "verb piel perfect 3rd common plur"},
                    {"h": "פָארֽוּר", "s": "H6289", "g": "properly", "m": "noun common"},
                ]
            },
            {
                "num": 12,
                "words": [
                    {"h": "אַיֵּה֙", "s": "H346", "g": "where?", "m": "particle"},
                    {"h": "מְע֣וֹן", "s": "H4583", "g": "an abode", "m": "noun common"},
                    {"h": "אֲרָי֔וֹת", "s": "H738", "g": "a lion", "m": "noun common"},
                    {"h": "וּמִרְעֶ֥ה", "s": "H4829", "g": "and pasture", "m": "conjunction + noun common"},
                    {"h": "ה֖וּא", "s": "H1931", "g": "he", "m": "pronoun plur"},
                    {"h": "לַכְּפִרִ֑ים", "s": "H3715", "g": "to/for a village", "m": "preposition + noun common"},
                    {"h": "אֲשֶׁ֣ר", "s": "H834", "g": "who", "m": "particle"},
                    {"h": "הָלַךְ֩", "s": "H1980", "g": "to walk", "m": "verb qal perfect 3rd masc sing"},
                    {"h": "אַרְיֵ֨ה", "s": "H738", "g": "in/with a lion", "m": "noun common"},
                    {"h": "לָבִ֥יא", "s": "H3833", "g": "and to roar", "m": "noun common"},
                    {"h": "שָׁ֛ם", "s": "H8033", "g": "there then", "m": "adverb"},
                    {"h": "גּ֥וּר", "s": "H1482", "g": "a cub", "m": "noun common"},
                    {"h": "אַרְיֵ֖ה", "s": "H738", "g": "in/with a lion", "m": "noun common"},
                    {"h": "וְאֵ֥ין", "s": "H369", "g": "and a non-entity", "m": "conjunction + particle"},
                    {"h": "מַחֲרִֽיד", "s": "H2729", "g": "to shudder with terror", "m": "verb hiphil participle active"},
                ]
            },
            {
                "num": 13,
                "words": [
                    {"h": "אַרְיֵ֤ה", "s": "H738", "g": "in/with a lion", "m": "noun common"},
                    {"h": "טֹרֵף֙", "s": "H2963", "g": "to pluck off or pull to pieces", "m": "verb qal participle active"},
                    {"h": "בְּדֵ֣י", "s": "H1767", "g": "in/with enough", "m": "preposition + noun common"},
                    {"h": "גֹֽרוֹתָ֔יו", "s": "H1484", "g": "{a cub", "m": "noun common + suffix"},
                    {"h": "וּמְחַנֵּ֖ק", "s": "H2614", "g": "and to be narrow", "m": "conjunction + verb piel participle active"},
                    {"h": "לְלִבְאֹתָ֑יו", "s": "H3833", "g": "to/for to roar", "m": "preposition + noun common + suffix"},
                    {"h": "וַיְמַלֵּא", "s": "H4390", "g": "and to fill or be full of", "m": "conjunction + verb piel sequential imperfect 3rd masc sing"},
                    {"h": "טֶ֣רֶף", "s": "H2964", "g": "something torn", "m": "noun common"},
                    {"h": "חֹרָ֔יו", "s": "H2356", "g": "a cavity", "m": "noun common + suffix"},
                    {"h": "וּמְעֹֽנֹתָ֖יו", "s": "H4585", "g": "and {an abode", "m": "conjunction + noun common + suffix"},
                    {"h": "טְרֵפָֽה", "s": "H2966", "g": "prey", "m": "noun common"},
                ]
            },
            {
                "num": 14,
                "words": [
                    {"h": "הִנְנִ֣י", "s": "H2005", "g": "lo!", "m": "particle + suffix"},
                    {"h": "אֵלַ֗יִךְ", "s": "H413", "g": "near", "m": "preposition + suffix"},
                    {"h": "נְאֻם֙", "s": "H5002", "g": "an oracle", "m": "noun common"},
                    {"h": "יְהוָ֣ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "צְבָא֔וֹת", "s": "H6635", "g": "in/with a mass of persons", "m": "noun common"},
                    {"h": "וְהִבְעַרְתִּ֤י", "s": "H1197", "g": "and to kindle", "m": "conjunction + verb hiphil perfect 1st common sing"},
                    {"h": "בֶֽעָשָׁן֙", "s": "H6227", "g": "in/with smoke", "m": "preposition + noun common"},
                    {"h": "רִכְבָּ֔הּ", "s": "H7393", "g": "a vehicle", "m": "noun common + suffix"},
                    {"h": "וּכְפִירַ֖יִךְ", "s": "H3715", "g": "and a village", "m": "conjunction + noun common + suffix"},
                    {"h": "תֹּ֣אכַל", "s": "H398", "g": "to eat", "m": "verb qal imperfect 3rd fem sing"},
                    {"h": "חָ֑רֶב", "s": "H2719", "g": "drought", "m": "noun common"},
                    {"h": "וְהִכְרַתִּ֤י", "s": "H3772", "g": "and to cut", "m": "conjunction + verb hiphil sequential perfect 1st common sing"},
                    {"h": "מֵאֶ֨רֶץ֙", "s": "H776", "g": "from the earth", "m": "preposition + noun common"},
                    {"h": "טַרְפֵּ֔ךְ", "s": "H2964", "g": "something torn", "m": "noun common + suffix"},
                    {"h": "וְלֹֽא", "s": "H3808", "g": "and not", "m": "conjunction + particle"},
                    {"h": "יִשָּׁמַ֥ע", "s": "H8085", "g": "attentively", "m": "verb niphal imperfect 3rd masc sing"},
                    {"h": "ע֖וֹד", "s": "H5750", "g": "properly", "m": "adverb"},
                    {"h": "ק֥וֹל", "s": "H6963", "g": "a voice or sound", "m": "noun common"},
                    {"h": "מַלְאָכֵֽכֵה", "s": "H4397", "g": "a messenger", "m": "noun common + suffix"},
                ]
            },
        ]
    },
    3: {
        "verses": [
            {
                "num": 1,
                "words": [
                    {"h": "ה֖וֹי", "s": "H1945", "g": "oh!", "m": "particle"},
                    {"h": "עִ֣יר", "s": "H5892", "g": "in/with a city in the widest sense", "m": "noun common"},
                    {"h": "דָּמִ֑ים", "s": "H1818", "g": "blood of man or an animal", "m": "noun common"},
                    {"h": "כֻּלָּ֗הּ", "s": "H3605", "g": "properly", "m": "noun common + suffix"},
                    {"h": "כַּ֤חַשׁ", "s": "H3585", "g": "literally a failure of flesh", "m": "noun common"},
                    {"h": "פֶּ֨רֶק֙", "s": "H6563", "g": "rapine", "m": "noun common"},
                    {"h": "מְלֵאָ֔ה", "s": "H4395", "g": "something fulfilled", "m": "adj"},
                    {"h": "לֹ֥א", "s": "H3808", "g": "not", "m": "particle"},
                    {"h": "יָמִ֖ישׁ", "s": "H4185", "g": "to withdraw", "m": "verb qal imperfect 3rd masc sing"},
                    {"h": "טָֽרֶף", "s": "H2964", "g": "something torn", "m": "noun common"},
                ]
            },
            {
                "num": 2,
                "words": [
                    {"h": "ק֣וֹל", "s": "H6963", "g": "a voice or sound", "m": "noun common"},
                    {"h": "שׁ֔וֹט", "s": "H7752", "g": "a lash", "m": "noun common"},
                    {"h": "וְק֖וֹל", "s": "H6963", "g": "and a voice or sound", "m": "conjunction + noun common"},
                    {"h": "רַ֣עַשׁ", "s": "H7494", "g": "vibration", "m": "noun common"},
                    {"h": "אוֹפָ֑ן", "s": "H212", "g": "a wheel", "m": "noun common"},
                    {"h": "וְס֣וּס", "s": "H5483", "g": "and + in/with a horse", "m": "conjunction + noun common"},
                    {"h": "דֹּהֵ֔ר", "s": "H1725", "g": "to curvet or move irregularly", "m": "verb qal participle active"},
                    {"h": "וּמֶרְכָּבָ֖ה", "s": "H4818", "g": "and a chariot", "m": "conjunction + noun common"},
                    {"h": "מְרַקֵּדָֽה", "s": "H7540", "g": "properly", "m": "verb piel participle active"},
                ]
            },
            {
                "num": 3,
                "words": [
                    {"h": "פָּרָ֣שׁ", "s": "H6571", "g": "in/with a steed", "m": "noun common"},
                    {"h": "מַעֲלֶ֗ה", "s": "H5927", "g": "to ascend", "m": "verb hiphil participle active"},
                    {"h": "וְלַ֤הַב", "s": "H3851", "g": "and a flash", "m": "conjunction + noun common"},
                    {"h": "חֶ֨רֶב֙", "s": "H2719", "g": "drought", "m": "noun common"},
                    {"h": "וּבְרַ֣ק", "s": "H1300", "g": "and + in/with lightning", "m": "conjunction + noun common"},
                    {"h": "חֲנִ֔ית", "s": "H2595", "g": "a lance", "m": "noun common"},
                    {"h": "וְרֹ֥ב", "s": "H7230", "g": "and abundance", "m": "conjunction + noun common"},
                    {"h": "חָלָ֖ל", "s": "H2491", "g": "pierced", "m": "adj"},
                    {"h": "וְכֹ֣בֶד", "s": "H3514", "g": "and weight", "m": "conjunction + noun common"},
                    {"h": "פָּ֑גֶר", "s": "H6297", "g": "a carcase", "m": "noun common"},
                    {"h": "וְאֵ֥ין", "s": "H369", "g": "and a non-entity", "m": "conjunction + particle"},
                    {"h": "קֵ֨צֶה֙", "s": "H7097", "g": "in/with an extremity", "m": "noun common"},
                    {"h": "לַגְּוִיָּ֔ה", "s": "H1472", "g": "to/for a body", "m": "preposition + noun common"},
                    {"h": "יכשלו", "s": "H3782", "g": "to totter or waver", "m": "verb niphal imperfect 3rd masc plur"},
                    {"h": "וְכָשְׁל֖וּ", "s": "H3782", "g": "and to totter or waver", "m": "conjunction + verb qal perfect 3rd common plur"},
                    {"h": "בִּגְוִיָּתָֽם", "s": "H1472", "g": "in/with a body", "m": "preposition + noun common + suffix"},
                ]
            },
            {
                "num": 4,
                "words": [
                    {"h": "מֵרֹב֙", "s": "H7230", "g": "from abundance", "m": "preposition + noun common"},
                    {"h": "זְנוּנֵ֣י", "s": "H2183", "g": "adultery", "m": "noun common"},
                    {"h": "זוֹנָ֔ה", "s": "H2181", "g": "to commit adultery", "m": "verb qal participle active"},
                    {"h": "ט֥וֹבַת", "s": "H2896", "g": "good in the widest sense", "m": "adj"},
                    {"h": "חֵ֖ן", "s": "H2580", "g": "graciousness", "m": "noun common"},
                    {"h": "בַּעֲלַ֣ת", "s": "H1172", "g": "a mistress", "m": "noun common"},
                    {"h": "כְּשָׁפִ֑ים", "s": "H3785", "g": "magic", "m": "noun common"},
                    {"h": "הַמֹּכֶ֤רֶת", "s": "H4376", "g": "the to sell", "m": "particle + verb qal participle active"},
                    {"h": "גּוֹיִם֙", "s": "H1471", "g": "a foreign nation", "m": "noun common"},
                    {"h": "בִּזְנוּנֶ֔יהָ", "s": "H2183", "g": "in/with adultery", "m": "preposition + noun common + suffix"},
                    {"h": "וּמִשְׁפָּח֖וֹת", "s": "H4940", "g": "and a family", "m": "conjunction + noun common"},
                    {"h": "בִּכְשָׁפֶֽיהָ", "s": "H3785", "g": "in/with magic", "m": "preposition + noun common + suffix"},
                ]
            },
            {
                "num": 5,
                "words": [
                    {"h": "הִנְנִ֣י", "s": "H2005", "g": "lo!", "m": "particle + suffix"},
                    {"h": "אֵלַ֗יִךְ", "s": "H413", "g": "near", "m": "preposition + suffix"},
                    {"h": "נְאֻם֙", "s": "H5002", "g": "an oracle", "m": "noun common"},
                    {"h": "יְהוָ֣ה", "s": "H3068", "g": "Jehovah", "m": "noun"},
                    {"h": "צְבָא֔וֹת", "s": "H6635", "g": "in/with a mass of persons", "m": "noun common"},
                    {"h": "וְגִלֵּיתִ֥י", "s": "H1540", "g": "and to denude", "m": "conjunction + verb piel perfect 1st common sing"},
                    {"h": "שׁוּלַ֖יִךְ", "s": "H7757", "g": "a skirt", "m": "noun common + suffix"},
                    {"h": "עַל", "s": "H5921", "g": "above", "m": "preposition"},
                    {"h": "פָּנָ֑יִךְ", "s": "H6440", "g": "the face", "m": "noun common + suffix"},
                    {"h": "וְהַרְאֵיתִ֤י", "s": "H7200", "g": "and to see", "m": "conjunction + verb hiphil perfect 1st common sing"},
                    {"h": "גוֹיִם֙", "s": "H1471", "g": "a foreign nation", "m": "noun common"},
                    {"h": "מַעְרֵ֔ךְ", "s": "H4626", "g": "a nude place", "m": "noun common + suffix"},
                    {"h": "וּמַמְלָכ֖וֹת", "s": "H4467", "g": "and dominion", "m": "conjunction + noun common"},
                    {"h": "קְלוֹנֵֽךְ", "s": "H7036", "g": "disgrace", "m": "noun common + suffix"},
                ]
            },
            {
                "num": 6,
                "words": [
                    {"h": "וְהִשְׁלַכְתִּ֥י", "s": "H7993", "g": "and to throw out", "m": "conjunction + verb hiphil perfect 1st common sing"},
                    {"h": "עָלַ֛יִךְ", "s": "H5921", "g": "above", "m": "preposition + suffix"},
                    {"h": "שִׁקֻּצִ֖ים", "s": "H8251", "g": "disgusting", "m": "noun common"},
                    {"h": "וְנִבַּלְתִּ֑יךְ", "s": "H5034", "g": "and to wilt", "m": "conjunction + verb piel perfect 1st common sing + suffix"},
                    {"h": "וְשַׂמְתִּ֖יךְ", "s": "H7760", "g": "and to put", "m": "conjunction + verb qal perfect 1st common sing + suffix"},
                    {"h": "כְּרֹֽאִי", "s": "H7210", "g": "as/like sight", "m": "preposition + noun common"},
                ]
            },
            {
                "num": 7,
                "words": [
                    {"h": "וְהָיָ֤ה", "s": "H1961", "g": "and to exist", "m": "conjunction + verb qal perfect 3rd masc sing"},
                    {"h": "כָל", "s": "H3605", "g": "properly", "m": "noun common"},
                    {"h": "רֹאַ֨יִךְ֙", "s": "H7200", "g": "to see", "m": "verb qal participle active + suffix"},
                    {"h": "יִדּ֣וֹד", "s": "H5074", "g": "properly", "m": "verb qal imperfect 3rd masc sing"},
                    {"h": "מִמֵּ֔ךְ", "s": "H4480", "g": "properly", "m": "preposition + suffix"},
                    {"h": "וְאָמַר֙", "s": "H559", "g": "and to say", "m": "conjunction + verb qal perfect 3rd masc sing"},
                    {"h": "שָׁדְּדָ֣ה", "s": "H7703", "g": "properly", "m": "verb pual perfect 3rd fem sing"},
                    {"h": "נִֽינְוֵ֔ה", "s": "H5210", "g": "Nineveh", "m": "noun"},
                    {"h": "מִ֖י", "s": "H4310", "g": "who?", "m": "particle"},
                    {"h": "יָנ֣וּד", "s": "H5110", "g": "to nod", "m": "verb qal imperfect 3rd masc sing"},
                    {"h": "לָ֑הּ", "g": "to/for", "m": "preposition + suffix"},
                    {"h": "מֵאַ֛יִן", "s": "H370", "g": "from where?", "m": "preposition + particle"},
                    {"h": "אֲבַקֵּ֥שׁ", "s": "H1245", "g": "to search out", "m": "verb piel imperfect 1st common sing"},
                    {"h": "מְנַחֲמִ֖ים", "s": "H5162", "g": "properly", "m": "verb piel participle active"},
                    {"h": "לָֽךְ", "g": "to/for", "m": "preposition + suffix"},
                ]
            },
            {
                "num": 8,
                "words": [
                    {"h": "הֲתֵֽיטְבִי֙", "s": "H3190", "g": "not to be make well", "m": "particle + verb hiphil imperfect 2nd fem sing"},
                    {"h": "מִנֹּ֣א", "s": "H4996", "g": "from No", "m": "preposition + noun"},
                    {"h": "אָמ֔וֹן", "s": "H528", "g": "Amon", "m": "noun"},
                    {"h": "הַיֹּֽשְׁבָה֙", "s": "H3427", "g": "the properly", "m": "particle + verb qal participle active"},
                    {"h": "בַּיְאֹרִ֔ים", "s": "H2975", "g": "in/with a channel", "m": "preposition + noun common"},
                    {"h": "מַ֖יִם", "s": "H4325", "g": "water", "m": "noun common"},
                    {"h": "סָבִ֣יב", "s": "H5439", "g": "a circle", "m": "noun common"},
                    {"h": "לָ֑הּ", "g": "to/for", "m": "preposition + suffix"},
                    {"h": "אֲשֶׁר", "s": "H834", "g": "who", "m": "particle"},
                    {"h": "חֵ֣יל", "s": "H2426", "g": "an army", "m": "noun common"},
                    {"h": "יָ֔ם", "s": "H3220", "g": "a sea or large body of water", "m": "noun common"},
                    {"h": "מִיָּ֖ם", "s": "H3220", "g": "from a sea or large body of water", "m": "preposition + noun common"},
                    {"h": "חוֹמָתָֽהּ", "s": "H2346", "g": "a wall of protection", "m": "noun common + suffix"},
                ]
            },
            {
                "num": 9,
                "words": [
                    {"h": "כּ֥וּשׁ", "s": "H3568", "g": "Cush", "m": "noun"},
                    {"h": "עָצְמָ֛ה", "s": "H6109", "g": "powerfulness", "m": "noun common + suffix"},
                    {"h": "וּמִצְרַ֖יִם", "s": "H4714", "g": "and Mitsrajim", "m": "conjunction + noun"},
                    {"h": "וְאֵ֣ין", "s": "H369", "g": "and a non-entity", "m": "conjunction + particle"},
                    {"h": "קֵ֑צֶה", "s": "H7097", "g": "in/with an extremity", "m": "noun common"},
                    {"h": "פּ֣וּט", "s": "H6316", "g": "Put", "m": "noun"},
                    {"h": "וְלוּבִ֔ים", "s": "H3864", "g": "and Lubim", "m": "conjunction + noun"},
                    {"h": "הָי֖וּ", "s": "H1961", "g": "to exist", "m": "verb qal perfect 3rd common plur"},
                    {"h": "בְּעֶזְרָתֵֽךְ", "s": "H5833", "g": "in/with aid", "m": "preposition + noun common + suffix"},
                ]
            },
            {
                "num": 10,
                "words": [
                    {"h": "גַּם", "s": "H1571", "g": "properly", "m": "particle"},
                    {"h": "הִ֗יא", "s": "H1931", "g": "he", "m": "pronoun plur"},
                    {"h": "לַגֹּלָה֙", "s": "H1473", "g": "to/for exile", "m": "preposition + noun common"},
                    {"h": "הָלְכָ֣ה", "s": "H1980", "g": "to walk", "m": "verb qal perfect 3rd fem sing"},
                    {"h": "בַשֶּׁ֔בִי", "s": "H7628", "g": "in/with exiled", "m": "preposition + noun common"},
                    {"h": "גַּ֧ם", "s": "H1571", "g": "properly", "m": "particle"},
                    {"h": "עֹלָלֶ֛יהָ", "s": "H5768", "g": "a suckling", "m": "noun common + suffix"},
                    {"h": "יְרֻטְּשׁ֖וּ", "s": "H7376", "g": "to dash down", "m": "verb pual imperfect 3rd masc plur"},
                    {"h": "בְּרֹ֣אשׁ", "s": "H7218", "g": "in/with the head", "m": "preposition + noun common"},
                    {"h": "כָּל", "s": "H3605", "g": "properly", "m": "noun common"},
                    {"h": "חוּצ֑וֹת", "s": "H2351", "g": "properly", "m": "noun common"},
                    {"h": "וְעַל", "s": "H5921", "g": "and above", "m": "conjunction + preposition"},
                    {"h": "נִכְבַּדֶּ֨יהָ֙", "s": "H3513", "g": "to be heavy", "m": "verb niphal participle passive + suffix"},
                    {"h": "יַדּ֣וּ", "s": "H3032", "g": "properly", "m": "verb qal perfect 3rd common plur"},
                    {"h": "גוֹרָ֔ל", "s": "H1486", "g": "properly", "m": "noun common"},
                    {"h": "וְכָל", "s": "H3605", "g": "and properly", "m": "conjunction + noun common"},
                    {"h": "גְּדוֹלֶ֖יהָ", "s": "H1419", "g": "great", "m": "adj + suffix"},
                    {"h": "רֻתְּק֥וּ", "s": "H7576", "g": "to fasten", "m": "verb pual perfect 3rd common plur"},
                    {"h": "בַזִּקִּֽים", "s": "H2131", "g": "in/with + in/with properly", "m": "preposition + noun common"},
                ]
            },
            {
                "num": 11,
                "words": [
                    {"h": "גַּם", "s": "H1571", "g": "properly", "m": "particle"},
                    {"h": "אַ֣תְּ", "s": "H859", "g": "and thou and thee", "m": "pronoun plur"},
                    {"h": "תִּשְׁכְּרִ֔י", "s": "H7937", "g": "to become tipsy", "m": "verb qal imperfect 2nd fem sing"},
                    {"h": "תְּהִ֖י", "s": "H1961", "g": "to exist", "m": "verb qal imperfect 3rd fem sing"},
                    {"h": "נַֽעֲלָמָ֑ה", "s": "H5956", "g": "to veil from sight", "m": "verb niphal participle passive"},
                    {"h": "גַּם", "s": "H1571", "g": "properly", "m": "particle"},
                    {"h": "אַ֛תְּ", "s": "H859", "g": "and thou and thee", "m": "pronoun plur"},
                    {"h": "תְּבַקְשִׁ֥י", "s": "H1245", "g": "to search out", "m": "verb piel imperfect 2nd fem sing"},
                    {"h": "מָע֖וֹז", "s": "H4581", "g": "a fortified place", "m": "noun common"},
                    {"h": "מֵאוֹיֵֽב", "s": "H341", "g": "from hating", "m": "preposition + verb qal participle active"},
                ]
            },
            {
                "num": 12,
                "words": [
                    {"h": "כָּ֨ל", "s": "H3605", "g": "properly", "m": "noun common"},
                    {"h": "מִבְצָרַ֔יִךְ", "s": "H4013", "g": "a fortification", "m": "noun common + suffix"},
                    {"h": "תְּאֵנִ֖ים", "s": "H8384", "g": "the fig", "m": "noun common"},
                    {"h": "עִם", "s": "H5973", "g": "adverb or preposition", "m": "preposition"},
                    {"h": "בִּכּוּרִ֑ים", "s": "H1061", "g": "the first-fruits of the crop", "m": "noun common"},
                    {"h": "אִם", "s": "H518", "g": "(and", "m": "conjunction"},
                    {"h": "יִנּ֕וֹעוּ", "s": "H5128", "g": "to waver", "m": "verb niphal imperfect 3rd masc plur"},
                    {"h": "וְנָפְל֖וּ", "s": "H5307", "g": "and to fall", "m": "conjunction + verb qal perfect 3rd common plur"},
                    {"h": "עַל", "s": "H5921", "g": "above", "m": "preposition"},
                    {"h": "פִּ֥י", "s": "H6310", "g": "the mouth", "m": "noun common"},
                    {"h": "אוֹכֵֽל", "s": "H398", "g": "to eat", "m": "verb qal participle active"},
                ]
            },
            {
                "num": 13,
                "words": [
                    {"h": "הִנֵּ֨ה", "s": "H2009", "g": "lo!", "m": "particle"},
                    {"h": "עַמֵּ֤ךְ", "s": "H5971", "g": "a people", "m": "noun common + suffix"},
                    {"h": "נָשִׁים֙", "s": "H802", "g": "a woman", "m": "noun common"},
                    {"h": "בְּקִרְבֵּ֔ךְ", "s": "H7130", "g": "in/with properly", "m": "preposition + noun common + suffix"},
                    {"h": "לְאֹ֣יְבַ֔יִךְ", "s": "H341", "g": "to/for hating", "m": "preposition + verb qal participle active + suffix"},
                    {"h": "פָּת֥וֹחַ", "s": "H6605", "g": "to open wide", "m": "verb qal infinitive absolute"},
                    {"h": "נִפְתְּח֖וּ", "s": "H6605", "g": "to open wide", "m": "verb niphal perfect 3rd common plur"},
                    {"h": "שַׁעֲרֵ֣י", "s": "H8179", "g": "an opening", "m": "noun common"},
                    {"h": "אַרְצֵ֑ךְ", "s": "H776", "g": "the earth", "m": "noun common + suffix"},
                    {"h": "אָכְלָ֥ה", "s": "H398", "g": "to eat", "m": "verb qal perfect 3rd fem sing"},
                    {"h": "אֵ֖שׁ", "s": "H784", "g": "fire", "m": "noun common"},
                    {"h": "בְּרִיחָֽיִך", "s": "H1280", "g": "a bolt", "m": "noun common + suffix"},
                ]
            },
            {
                "num": 14,
                "words": [
                    {"h": "מֵ֤י", "s": "H4325", "g": "water", "m": "noun common"},
                    {"h": "מָצוֹר֙", "s": "H4692", "g": "something hemming in", "m": "noun common"},
                    {"h": "שַֽׁאֲבִי", "s": "H7579", "g": "to bale up water", "m": "verb qal imperative 2nd fem sing"},
                    {"h": "לָ֔ךְ", "g": "to/for", "m": "preposition + suffix"},
                    {"h": "חַזְּקִ֖י", "s": "H2388", "g": "to fasten upon", "m": "verb piel imperative 2nd fem sing"},
                    {"h": "מִבְצָרָ֑יִךְ", "s": "H4013", "g": "a fortification", "m": "noun common + suffix"},
                    {"h": "בֹּ֧אִי", "s": "H935", "g": "to go or come", "m": "verb qal imperative 2nd fem sing"},
                    {"h": "בַטִּ֛יט", "s": "H2916", "g": "in/with mud or clay", "m": "preposition + noun common"},
                    {"h": "וְרִמְסִ֥י", "s": "H7429", "g": "and to tread upon", "m": "conjunction + verb qal imperative 2nd fem sing"},
                    {"h": "בַחֹ֖מֶר", "s": "H2563", "g": "in/with properly", "m": "preposition + noun common"},
                    {"h": "הַחֲזִ֥יקִי", "s": "H2388", "g": "to fasten upon", "m": "verb hiphil imperative 2nd fem sing"},
                    {"h": "מַלְבֵּֽן", "s": "H4404", "g": "a brickkiln", "m": "noun common"},
                ]
            },
            {
                "num": 15,
                "words": [
                    {"h": "שָׁ֚ם", "s": "H8033", "g": "there then", "m": "adverb"},
                    {"h": "תֹּאכְלֵ֣ךְ", "s": "H398", "g": "to eat", "m": "verb qal imperfect 3rd fem sing + suffix"},
                    {"h": "אֵ֔שׁ", "s": "H784", "g": "fire", "m": "noun common"},
                    {"h": "תַּכְרִיתֵ֣ךְ", "s": "H3772", "g": "to cut", "m": "verb hiphil imperfect 3rd fem sing + suffix"},
                    {"h": "חֶ֔רֶב", "s": "H2719", "g": "drought", "m": "noun common"},
                    {"h": "תֹּאכְלֵ֖ךְ", "s": "H398", "g": "to eat", "m": "verb qal imperfect 3rd fem sing + suffix"},
                    {"h": "כַּיָּ֑לֶק", "s": "H3218", "g": "as/like a devourer", "m": "preposition + noun common"},
                    {"h": "הִתְכַּבֵּ֣ד", "s": "H3513", "g": "to be heavy", "m": "verb hithpael imperative 2nd masc sing"},
                    {"h": "כַּיֶּ֔לֶק", "s": "H3218", "g": "as/like a devourer", "m": "preposition + noun common"},
                    {"h": "הִֽתְכַּבְּדִ֖י", "s": "H3513", "g": "to be heavy", "m": "verb hithpael imperative 2nd fem sing"},
                    {"h": "כָּאַרְבֶּֽה", "s": "H697", "g": "as/like a locust", "m": "preposition + noun common"},
                ]
            },
            {
                "num": 16,
                "words": [
                    {"h": "הִרְבֵּית֙", "s": "H7235", "g": "to increase", "m": "verb hiphil perfect 2nd fem sing"},
                    {"h": "רֹֽכְלַ֔יִךְ", "s": "H7402", "g": "to travel for trading", "m": "verb qal participle active + suffix"},
                    {"h": "מִכּוֹכְבֵ֖י", "s": "H3556", "g": "from a star", "m": "preposition + noun common"},
                    {"h": "הַשָּׁמָ֑יִם", "s": "H8064", "g": "the the sky (as aloft", "m": "particle + noun common"},
                    {"h": "יֶ֥לֶק", "s": "H3218", "g": "a devourer", "m": "noun common"},
                    {"h": "פָּשַׁ֖ט", "s": "H6584", "g": "to spread out", "m": "verb qal perfect 3rd masc sing"},
                    {"h": "וַיָּעֹֽף", "s": "H5774", "g": "and to fly", "m": "conjunction + verb qal sequential imperfect 3rd masc sing"},
                ]
            },
            {
                "num": 17,
                "words": [
                    {"h": "מִנְּזָרַ֨יִךְ֙", "s": "H4502", "g": "a prince", "m": "noun common + suffix"},
                    {"h": "כָּֽאַרְבֶּ֔ה", "s": "H697", "g": "as/like a locust", "m": "preposition + noun common"},
                    {"h": "וְטַפְסְרַ֖יִךְ", "s": "H2951", "g": "and a military governor", "m": "conjunction + noun common + suffix"},
                    {"h": "כְּג֣וֹב", "s": "H1462", "g": "as/like the locust", "m": "preposition + noun common"},
                    {"h": "גֹּבָ֑י", "s": "H1462", "g": "in/with the locust", "m": "noun common"},
                    {"h": "הַֽחוֹנִ֤ים", "s": "H2583", "g": "the properly", "m": "particle + verb qal participle active"},
                    {"h": "בַּגְּדֵרוֹת֙", "s": "H1448", "g": "in/with enclosure", "m": "preposition + noun common"},
                    {"h": "בְּי֣וֹם", "s": "H3117", "g": "in/with a day", "m": "preposition + noun common"},
                    {"h": "קָרָ֔ה", "s": "H7135", "g": "coolness", "m": "noun common"},
                    {"h": "שֶׁ֤מֶשׁ", "s": "H8121", "g": "the sun", "m": "noun common"},
                    {"h": "זָֽרְחָה֙", "s": "H2224", "g": "properly", "m": "verb qal perfect 3rd fem sing"},
                    {"h": "וְנוֹדַ֔ד", "s": "H5074", "g": "and properly", "m": "conjunction + verb poal perfect 3rd masc sing"},
                    {"h": "וְלֹֽא", "s": "H3808", "g": "and not", "m": "conjunction + particle"},
                    {"h": "נוֹדַ֥ע", "s": "H3045", "g": "to know", "m": "verb niphal perfect 3rd masc sing"},
                    {"h": "מְקוֹמ֖וֹ", "s": "H4725", "g": "properly", "m": "noun common + suffix"},
                    {"h": "אַיָּֽם", "s": "H335", "g": "where? hence how?", "m": "particle + suffix"},
                ]
            },
            {
                "num": 18,
                "words": [
                    {"h": "נָמ֤וּ", "s": "H5123", "g": "to slumber", "m": "verb qal perfect 3rd common plur"},
                    {"h": "רֹעֶ֨יךָ֙", "s": "H7462", "g": "in/with to tend a flock", "m": "verb qal participle active + suffix"},
                    {"h": "מֶ֣לֶךְ", "s": "H4428", "g": "a king", "m": "noun common"},
                    {"h": "אַשּׁ֔וּר", "s": "H804", "g": "Ashshur", "m": "noun"},
                    {"h": "יִשְׁכְּנ֖וּ", "s": "H7931", "g": "to reside or permanently stay", "m": "verb qal imperfect 3rd masc plur"},
                    {"h": "אַדִּירֶ֑יךָ", "s": "H117", "g": "wide or large", "m": "adj + suffix"},
                    {"h": "נָפֹ֧שׁוּ", "s": "H6335", "g": "in/with to spread", "m": "verb niphal perfect 3rd common plur"},
                    {"h": "עַמְּךָ֛", "s": "H5971", "g": "a people", "m": "noun common + suffix"},
                    {"h": "עַל", "s": "H5921", "g": "above", "m": "preposition"},
                    {"h": "הֶהָרִ֖ים", "s": "H2022", "g": "the a mountain or range of hills", "m": "particle + noun common"},
                    {"h": "וְאֵ֥ין", "s": "H369", "g": "and a non-entity", "m": "conjunction + particle"},
                    {"h": "מְקַבֵּֽץ", "s": "H6908", "g": "to grasp", "m": "verb piel participle active"},
                ]
            },
            {
                "num": 19,
                "words": [
                    {"h": "אֵין", "s": "H369", "g": "a non-entity", "m": "particle"},
                    {"h": "כֵּהָ֣ה", "s": "H3545", "g": "properly", "m": "noun common"},
                    {"h": "לְשִׁבְרֶ֔ךָ", "s": "H7667", "g": "to/for a fracture", "m": "preposition + noun common + suffix"},
                    {"h": "נַחְלָ֖ה", "s": "H2470", "g": "properly", "m": "verb niphal participle passive"},
                    {"h": "מַכָּתֶ֑ךָ", "s": "H4347", "g": "a wound", "m": "noun common + suffix"},
                    {"h": "כֹּ֣ל", "s": "H3605", "g": "properly", "m": "noun common"},
                    {"h": "שֹׁמְעֵ֣י", "s": "H8085", "g": "attentively", "m": "verb qal participle active"},
                    {"h": "שִׁמְעֲךָ֗", "s": "H8088", "g": "in/with something heard", "m": "noun common + suffix"},
                    {"h": "תָּ֤קְעוּ", "s": "H8628", "g": "to clatter", "m": "verb qal perfect 3rd common plur"},
                    {"h": "כַף֙", "s": "H3709", "g": "the hollow hand or palm", "m": "noun common"},
                    {"h": "עָלֶ֔יךָ", "s": "H5921", "g": "above", "m": "preposition + suffix"},
                    {"h": "כִּ֗י", "s": "H3588", "g": "and", "m": "conjunction"},
                    {"h": "עַל", "s": "H5921", "g": "above", "m": "preposition"},
                    {"h": "מִ֛י", "s": "H4310", "g": "who?", "m": "particle"},
                    {"h": "לֹֽא", "s": "H3808", "g": "not", "m": "particle"},
                    {"h": "עָבְרָ֥ה", "s": "H5674", "g": "to cross over", "m": "verb qal perfect 3rd fem sing"},
                    {"h": "רָעָתְךָ֖", "s": "H7451", "g": "and bad or evil", "m": "noun common + suffix"},
                    {"h": "תָּמִֽיד", "s": "H8548", "g": "properly", "m": "noun common"},
                ]
            },
        ]
    },
}
