"""
Auto-generated interlinear Greek-English data for Philemon.

Source: MorphGNT SBLGNT (https://github.com/morphgnt/sblgnt) — CC-BY-SA 3.0
        Strong's Greek Dictionary (openscriptures) — CC-BY 4.0

Generated by build_nt_interlinear.py

Keys:  h = Greek text (with accents) — same slot as Hebrew "h"
       t = transliteration
       s = Strong's G-number
       g = English gloss — same slot as Hebrew "g"
       m = morphology
       l = lexical lemma
"""

INTERLINEAR_NT_PHILEMON = {
    1: {
        "verses": [
            {
                "num": 1,
                "words": [
                    {"h": "Παῦλος", "t": "Paûlos", "s": "G3972", "g": "Paul", "m": "noun nominative singular masculine"},
                    {"h": "δέσμιος", "t": "désmios", "s": "G1198", "g": "in bonds", "m": "noun nominative singular masculine"},
                    {"h": "Χριστοῦ", "t": "Christós", "s": "G5547", "g": "Christ", "m": "noun genitive singular masculine", "l": "Χριστός"},
                    {"h": "Ἰησοῦ", "t": "Iēsoûs", "s": "G2424", "g": "Jesus", "m": "noun genitive singular masculine", "l": "Ἰησοῦς"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "Τιμόθεος", "t": "Timótheos", "s": "G5095", "g": "Timotheus", "m": "noun nominative singular masculine"},
                    {"h": "ὁ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular masculine"},
                    {"h": "ἀδελφὸς", "t": "adelphós", "s": "G80", "g": "brother", "m": "noun nominative singular masculine", "l": "ἀδελφός"},
                    {"h": "Φιλήμονι", "t": "Philḗmōn", "s": "G5371", "g": "Philemon", "m": "noun dative singular masculine", "l": "Φιλήμων"},
                    {"h": "τῷ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular masculine", "l": "ὁ"},
                    {"h": "ἀγαπητῷ", "t": "agapētós", "s": "G27", "g": "(dearly", "m": "adjective dative singular masculine", "l": "ἀγαπητός"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "συνεργῷ", "t": "synergós", "s": "G4904", "g": "companion in labour", "m": "adjective dative singular masculine", "l": "συνεργός"},
                    {"h": "ἡμῶν", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive plural", "l": "ἐγώ"},
                ]
            },
            {
                "num": 2,
                "words": [
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "Ἀπφίᾳ", "t": "Apphía", "s": "G682", "g": "Apphia", "m": "noun dative singular feminine", "l": "Ἀπφία"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "⸀ἀδελφῇ", "t": "adelphḗ", "s": "G79", "g": "sister", "m": "noun dative singular feminine", "l": "ἀδελφή"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "Ἀρχίππῳ", "t": "Árchippos", "s": "G751", "g": "Archippus", "m": "noun dative singular masculine", "l": "Ἄρχιππος"},
                    {"h": "τῷ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular masculine", "l": "ὁ"},
                    {"h": "συστρατιώτῃ", "t": "systratiṓtēs", "s": "G4961", "g": "fellowsoldier", "m": "noun dative singular masculine", "l": "συστρατιώτης"},
                    {"h": "ἡμῶν", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive plural", "l": "ἐγώ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "κατ’", "t": "katá", "s": "G2596", "g": "about", "m": "preposition", "l": "κατά"},
                    {"h": "οἶκόν", "t": "oîkos", "s": "G3624", "g": "home", "m": "noun accusative singular masculine", "l": "οἶκος"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ἐκκλησίᾳ", "t": "ekklēsía", "s": "G1577", "g": "assembly", "m": "noun dative singular feminine", "l": "ἐκκλησία"},
                ]
            },
            {
                "num": 3,
                "words": [
                    {"h": "χάρις", "t": "cháris", "s": "G5485", "g": "acceptable", "m": "noun nominative singular feminine"},
                    {"h": "ὑμῖν", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative plural", "l": "σύ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "εἰρήνη", "t": "eirḗnē", "s": "G1515", "g": "one", "m": "noun nominative singular feminine"},
                    {"h": "ἀπὸ", "t": "apó", "s": "G575", "g": "after", "m": "preposition", "l": "ἀπό"},
                    {"h": "θεοῦ", "t": "theós", "s": "G2316", "g": "X exceeding", "m": "noun genitive singular masculine", "l": "θεός"},
                    {"h": "πατρὸς", "t": "patḗr", "s": "G3962", "g": "father", "m": "noun genitive singular masculine", "l": "πατήρ"},
                    {"h": "ἡμῶν", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive plural", "l": "ἐγώ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "κυρίου", "t": "kýrios", "s": "G2962", "g": "God", "m": "noun genitive singular masculine", "l": "κύριος"},
                    {"h": "Ἰησοῦ", "t": "Iēsoûs", "s": "G2424", "g": "Jesus", "m": "noun genitive singular masculine", "l": "Ἰησοῦς"},
                    {"h": "Χριστοῦ", "t": "Christós", "s": "G5547", "g": "Christ", "m": "noun genitive singular masculine", "l": "Χριστός"},
                ]
            },
            {
                "num": 4,
                "words": [
                    {"h": "Εὐχαριστῶ", "t": "eucharistéō", "s": "G2168", "g": "thank(-ful", "m": "verb 1st present active indicative singular", "l": "εὐχαριστέω"},
                    {"h": "τῷ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular masculine", "l": "ὁ"},
                    {"h": "θεῷ", "t": "theós", "s": "G2316", "g": "X exceeding", "m": "noun dative singular masculine", "l": "θεός"},
                    {"h": "μου", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive singular", "l": "ἐγώ"},
                    {"h": "πάντοτε", "t": "pántote", "s": "G3842", "g": "alway", "m": "adverb"},
                    {"h": "μνείαν", "t": "mneía", "s": "G3417", "g": "mention", "m": "noun accusative singular feminine", "l": "μνεία"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ποιούμενος", "t": "poiéō", "s": "G4160", "g": "abide", "m": "verb present middle participle nominative singular masculine", "l": "ποιέω"},
                    {"h": "ἐπὶ", "t": "epí", "s": "G1909", "g": "about", "m": "preposition", "l": "ἐπί"},
                    {"h": "τῶν", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive plural feminine", "l": "ὁ"},
                    {"h": "προσευχῶν", "t": "proseuchḗ", "s": "G4335", "g": "X pray earnestly", "m": "noun genitive plural feminine", "l": "προσευχή"},
                    {"h": "μου", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive singular", "l": "ἐγώ"},
                ]
            },
            {
                "num": 5,
                "words": [
                    {"h": "ἀκούων", "t": "akoúō", "s": "G191", "g": "give  audience", "m": "verb present active participle nominative singular masculine", "l": "ἀκούω"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "τὴν", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular feminine", "l": "ὁ"},
                    {"h": "ἀγάπην", "t": "agápē", "s": "G26", "g": "charity", "m": "noun accusative singular feminine", "l": "ἀγάπη"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "τὴν", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular feminine", "l": "ὁ"},
                    {"h": "πίστιν", "t": "pístis", "s": "G4102", "g": "assurance", "m": "noun accusative singular feminine", "l": "πίστις"},
                    {"h": "ἣν", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative singular feminine", "l": "ὅς"},
                    {"h": "ἔχεις", "t": "échō", "s": "G2192", "g": "be (able", "m": "verb 2nd present active indicative singular", "l": "ἔχω"},
                    {"h": "⸀πρὸς", "t": "prós", "s": "G4314", "g": "about", "m": "preposition", "l": "πρός"},
                    {"h": "τὸν", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular masculine", "l": "ὁ"},
                    {"h": "κύριον", "t": "kýrios", "s": "G2962", "g": "God", "m": "noun accusative singular masculine", "l": "κύριος"},
                    {"h": "Ἰησοῦν", "t": "Iēsoûs", "s": "G2424", "g": "Jesus", "m": "noun accusative singular masculine", "l": "Ἰησοῦς"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "εἰς", "t": "heîs", "s": "G1520", "g": "a(-n", "m": "preposition"},
                    {"h": "πάντας", "t": "pâs", "s": "G3956", "g": "all (manner of", "m": "adjective accusative plural masculine", "l": "πᾶς"},
                    {"h": "τοὺς", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural masculine", "l": "ὁ"},
                    {"h": "ἁγίους", "t": "hágios", "s": "G40", "g": "holy (one", "m": "adjective accusative plural masculine", "l": "ἅγιος"},
                ]
            },
            {
                "num": 6,
                "words": [
                    {"h": "ὅπως", "t": "hópōs", "s": "G3704", "g": "because", "m": "conjunction"},
                    {"h": "ἡ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular feminine", "l": "ὁ"},
                    {"h": "κοινωνία", "t": "koinōnía", "s": "G2842", "g": "communicate", "m": "noun nominative singular feminine"},
                    {"h": "τῆς", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular feminine", "l": "ὁ"},
                    {"h": "πίστεώς", "t": "pístis", "s": "G4102", "g": "assurance", "m": "noun genitive singular feminine", "l": "πίστις"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ἐνεργὴς", "t": "energḗs", "s": "G1756", "g": "effectual", "m": "adjective nominative singular feminine", "l": "ἐνεργής"},
                    {"h": "γένηται", "t": "gínomai", "s": "G1096", "g": "arise", "m": "verb 3rd aorist middle subjunctive singular", "l": "γίνομαι"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "ἐπιγνώσει", "t": "epígnōsis", "s": "G1922", "g": "knowledge(-ing", "m": "noun dative singular feminine", "l": "ἐπίγνωσις"},
                    {"h": "παντὸς", "t": "pâs", "s": "G3956", "g": "all (manner of", "m": "adjective genitive singular neuter", "l": "πᾶς"},
                    {"h": "ἀγαθοῦ", "t": "agathós", "s": "G18", "g": "benefit", "m": "adjective genitive singular neuter", "l": "ἀγαθός"},
                    {"h": "⸀τοῦ", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular neuter", "l": "ὁ"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "ἡμῖν", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun dative plural", "l": "ἐγώ"},
                    {"h": "εἰς", "t": "heîs", "s": "G1520", "g": "a(-n", "m": "preposition"},
                    {"h": "⸀Χριστόν", "t": "Christós", "s": "G5547", "g": "Christ", "m": "noun accusative singular masculine", "l": "Χριστός"},
                ]
            },
            {
                "num": 7,
                "words": [
                    {"h": "⸀χαρὰν", "t": "chará", "s": "G5479", "g": "gladness", "m": "noun accusative singular feminine", "l": "χαρά"},
                    {"h": "γὰρ", "t": "gár", "s": "G1063", "g": "and", "m": "conjunction", "l": "γάρ"},
                    {"h": "⸂πολλὴν", "t": "polýs", "s": "G4183", "g": "abundant", "m": "adjective accusative singular feminine", "l": "πολύς"},
                    {"h": "ἔσχον⸃", "t": "échō", "s": "G2192", "g": "be (able", "m": "verb 1st aorist active indicative singular", "l": "ἔχω"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "παράκλησιν", "t": "paráklēsis", "s": "G3874", "g": "comfort", "m": "noun accusative singular feminine", "l": "παράκλησις"},
                    {"h": "ἐπὶ", "t": "epí", "s": "G1909", "g": "about", "m": "preposition", "l": "ἐπί"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "ἀγάπῃ", "t": "agápē", "s": "G26", "g": "charity", "m": "noun dative singular feminine", "l": "ἀγάπη"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ὅτι", "t": "hóti", "s": "G3754", "g": "as concerning that", "m": "conjunction"},
                    {"h": "τὰ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative plural neuter", "l": "ὁ"},
                    {"h": "σπλάγχνα", "t": "splánchnon", "s": "G4698", "g": "bowels", "m": "noun nominative plural neuter", "l": "σπλάγχνον"},
                    {"h": "τῶν", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive plural masculine", "l": "ὁ"},
                    {"h": "ἁγίων", "t": "hágios", "s": "G40", "g": "holy (one", "m": "adjective genitive plural masculine", "l": "ἅγιος"},
                    {"h": "ἀναπέπαυται", "t": "anapaúō", "s": "G373", "g": "take ease", "m": "verb 3rd perfect passive indicative singular", "l": "ἀναπαύω"},
                    {"h": "διὰ", "t": "diá", "s": "G1223", "g": "after", "m": "preposition", "l": "διά"},
                    {"h": "σοῦ", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ἀδελφέ", "t": "adelphós", "s": "G80", "g": "brother", "m": "noun singular masculine", "l": "ἀδελφός"},
                ]
            },
            {
                "num": 8,
                "words": [
                    {"h": "Διό", "t": "dió", "s": "G1352", "g": "for which cause", "m": "conjunction", "l": "διό"},
                    {"h": "πολλὴν", "t": "polýs", "s": "G4183", "g": "abundant", "m": "adjective accusative singular feminine", "l": "πολύς"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "Χριστῷ", "t": "Christós", "s": "G5547", "g": "Christ", "m": "noun dative singular masculine", "l": "Χριστός"},
                    {"h": "παρρησίαν", "t": "parrhēsía", "s": "G3954", "g": "bold (X -ly", "m": "noun accusative singular feminine", "l": "παρρησία"},
                    {"h": "ἔχων", "t": "échō", "s": "G2192", "g": "be (able", "m": "verb present active participle nominative singular masculine", "l": "ἔχω"},
                    {"h": "ἐπιτάσσειν", "t": "epitássō", "s": "G2004", "g": "charge", "m": "verb present active infinitive", "l": "ἐπιτάσσω"},
                    {"h": "σοι", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "τὸ", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular neuter", "l": "ὁ"},
                    {"h": "ἀνῆκον", "t": "anḗkō", "s": "G433", "g": "convenient", "m": "verb present active participle accusative singular neuter", "l": "ἀνήκω"},
                ]
            },
            {
                "num": 9,
                "words": [
                    {"h": "διὰ", "t": "diá", "s": "G1223", "g": "after", "m": "preposition", "l": "διά"},
                    {"h": "τὴν", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular feminine", "l": "ὁ"},
                    {"h": "ἀγάπην", "t": "agápē", "s": "G26", "g": "charity", "m": "noun accusative singular feminine", "l": "ἀγάπη"},
                    {"h": "μᾶλλον", "t": "mâllon", "s": "G3123", "g": "+ better", "m": "adverb"},
                    {"h": "παρακαλῶ", "t": "parakaléō", "s": "G3870", "g": "beseech", "m": "verb 1st present active indicative singular", "l": "παρακαλέω"},
                    {"h": "τοιοῦτος", "t": "toioûtos", "s": "G5108", "g": "like", "m": "demonstrative nominative singular masculine"},
                    {"h": "ὢν", "t": "eimí", "s": "G1510", "g": "am", "m": "verb present active participle nominative singular masculine", "l": "εἰμί"},
                    {"h": "ὡς", "t": "hōs", "s": "G5613", "g": "about", "m": "conjunction"},
                    {"h": "Παῦλος", "t": "Paûlos", "s": "G3972", "g": "Paul", "m": "noun nominative singular masculine"},
                    {"h": "πρεσβύτης", "t": "presbýtēs", "s": "G4246", "g": "aged", "m": "noun nominative singular masculine"},
                    {"h": "νυνὶ", "t": "nyní", "s": "G3570", "g": "now", "m": "adverb", "l": "νυνί"},
                    {"h": "δὲ", "t": "dé", "s": "G1161", "g": "also", "m": "conjunction", "l": "δέ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "adverb", "l": "καί"},
                    {"h": "δέσμιος", "t": "désmios", "s": "G1198", "g": "in bonds", "m": "noun nominative singular masculine"},
                    {"h": "⸂Χριστοῦ", "t": "Christós", "s": "G5547", "g": "Christ", "m": "noun genitive singular masculine", "l": "Χριστός"},
                    {"h": "Ἰησοῦ⸃—", "t": "Iēsoûs", "s": "G2424", "g": "Jesus", "m": "noun genitive singular masculine", "l": "Ἰησοῦς"},
                ]
            },
            {
                "num": 10,
                "words": [
                    {"h": "παρακαλῶ", "t": "parakaléō", "s": "G3870", "g": "beseech", "m": "verb 1st present active indicative singular", "l": "παρακαλέω"},
                    {"h": "σε", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun accusative singular", "l": "σύ"},
                    {"h": "περὶ", "t": "perí", "s": "G4012", "g": "about", "m": "preposition", "l": "περί"},
                    {"h": "τοῦ", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular neuter", "l": "ὁ"},
                    {"h": "ἐμοῦ", "t": "emós", "s": "G1699", "g": "of me", "m": "adjective genitive singular neuter", "l": "ἐμός"},
                    {"h": "τέκνου", "t": "téknon", "s": "G5043", "g": "child", "m": "noun genitive singular neuter", "l": "τέκνον"},
                    {"h": "ὃν", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative singular masculine", "l": "ὅς"},
                    {"h": "ἐγέννησα", "t": "gennáō", "s": "G1080", "g": "bear", "m": "verb 1st aorist active indicative singular", "l": "γεννάω"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "τοῖς", "t": "ho", "s": "G3588", "g": "the", "m": "article dative plural masculine", "l": "ὁ"},
                    {"h": "⸀δεσμοῖς", "m": "noun dative plural masculine", "l": "δεσμός"},
                    {"h": "Ὀνήσιμον", "t": "Onḗsimos", "s": "G3682", "g": "Onesimus", "m": "noun accusative singular masculine", "l": "Ὀνήσιμος"},
                ]
            },
            {
                "num": 11,
                "words": [
                    {"h": "τόν", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular masculine", "l": "ὁ"},
                    {"h": "ποτέ", "t": "póte", "s": "G4219", "g": "+ how long", "m": "particle"},
                    {"h": "σοι", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "ἄχρηστον", "t": "áchrēstos", "s": "G890", "g": "unprofitable", "m": "adjective accusative singular masculine", "l": "ἄχρηστος"},
                    {"h": "νυνὶ", "t": "nyní", "s": "G3570", "g": "now", "m": "adverb", "l": "νυνί"},
                    {"h": "⸀δὲ", "t": "dé", "s": "G1161", "g": "also", "m": "conjunction", "l": "δέ"},
                    {"h": "σοὶ", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "ἐμοὶ", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun dative singular", "l": "ἐγώ"},
                    {"h": "εὔχρηστον", "t": "eúchrēstos", "s": "G2173", "g": "profitable", "m": "adjective accusative singular masculine", "l": "εὔχρηστος"},
                ]
            },
            {
                "num": 12,
                "words": [
                    {"h": "ὃν", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative singular masculine", "l": "ὅς"},
                    {"h": "ἀνέπεμψά", "t": "anapémpō", "s": "G375", "g": "send", "m": "verb 1st aorist active indicative singular", "l": "ἀναπέμπω"},
                    {"h": "⸂σοι", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "αὐτόν", "t": "autós", "s": "G846", "g": "her", "m": "personal pronoun accusative singular masculine", "l": "αὐτός"},
                    {"h": "τοῦτ’", "t": "hoûtos", "s": "G3778", "g": "he", "m": "demonstrative nominative singular neuter", "l": "οὗτος"},
                    {"h": "ἔστιν", "t": "eimí", "s": "G1510", "g": "am", "m": "verb 3rd present active indicative singular", "l": "εἰμί"},
                    {"h": "τὰ", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural neuter", "l": "ὁ"},
                    {"h": "ἐμὰ", "t": "emós", "s": "G1699", "g": "of me", "m": "adjective accusative plural neuter", "l": "ἐμός"},
                    {"h": "σπλάγχνα⸃", "t": "splánchnon", "s": "G4698", "g": "bowels", "m": "noun accusative plural neuter", "l": "σπλάγχνον"},
                ]
            },
            {
                "num": 13,
                "words": [
                    {"h": "ὃν", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative singular masculine", "l": "ὅς"},
                    {"h": "ἐγὼ", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun nominative singular", "l": "ἐγώ"},
                    {"h": "ἐβουλόμην", "t": "boúlomai", "s": "G1014", "g": "be disposed", "m": "verb 1st imperfect middle indicative singular", "l": "βούλομαι"},
                    {"h": "πρὸς", "t": "prós", "s": "G4314", "g": "about", "m": "preposition", "l": "πρός"},
                    {"h": "ἐμαυτὸν", "t": "emautoû", "s": "G1683", "g": "me", "m": "personal pronoun accusative singular masculine", "l": "ἐμαυτοῦ"},
                    {"h": "κατέχειν", "t": "katéchō", "s": "G2722", "g": "have", "m": "verb present active infinitive", "l": "κατέχω"},
                    {"h": "ἵνα", "t": "hína", "s": "G2443", "g": "albeit", "m": "conjunction"},
                    {"h": "ὑπὲρ", "t": "hypér", "s": "G5228", "g": "(+ exceeding", "m": "preposition", "l": "ὑπέρ"},
                    {"h": "σοῦ", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "⸂μοι", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun dative singular", "l": "ἐγώ"},
                    {"h": "διακονῇ⸃", "t": "diakonéō", "s": "G1247", "g": "minister", "m": "verb 3rd present active subjunctive singular", "l": "διακονέω"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "τοῖς", "t": "ho", "s": "G3588", "g": "the", "m": "article dative plural masculine", "l": "ὁ"},
                    {"h": "δεσμοῖς", "m": "noun dative plural masculine", "l": "δεσμός"},
                    {"h": "τοῦ", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular neuter", "l": "ὁ"},
                    {"h": "εὐαγγελίου", "t": "euangélion", "s": "G2098", "g": "gospel", "m": "noun genitive singular neuter", "l": "εὐαγγέλιον"},
                ]
            },
            {
                "num": 14,
                "words": [
                    {"h": "χωρὶς", "t": "chōrís", "s": "G5565", "g": "beside", "m": "preposition", "l": "χωρίς"},
                    {"h": "δὲ", "t": "dé", "s": "G1161", "g": "also", "m": "conjunction", "l": "δέ"},
                    {"h": "τῆς", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular feminine", "l": "ὁ"},
                    {"h": "σῆς", "t": "sós", "s": "G4674", "g": "thine", "m": "adjective genitive singular feminine", "l": "σός"},
                    {"h": "γνώμης", "t": "gnṓmē", "s": "G1106", "g": "advice", "m": "noun genitive singular feminine", "l": "γνώμη"},
                    {"h": "οὐδὲν", "t": "oudeís", "s": "G3762", "g": "any", "m": "adjective accusative singular neuter", "l": "οὐδείς"},
                    {"h": "ἠθέλησα", "t": "thélō", "s": "G2309", "g": "desire", "m": "verb 1st aorist active indicative singular", "l": "θέλω"},
                    {"h": "ποιῆσαι", "t": "poiéō", "s": "G4160", "g": "abide", "m": "verb aorist active infinitive", "l": "ποιέω"},
                    {"h": "ἵνα", "t": "hína", "s": "G2443", "g": "albeit", "m": "conjunction"},
                    {"h": "μὴ", "t": "mḗ", "s": "G3361", "g": "any but", "m": "adverb", "l": "μή"},
                    {"h": "ὡς", "t": "hōs", "s": "G5613", "g": "about", "m": "conjunction"},
                    {"h": "κατὰ", "t": "katá", "s": "G2596", "g": "about", "m": "preposition", "l": "κατά"},
                    {"h": "ἀνάγκην", "t": "anánkē", "s": "G318", "g": "distress", "m": "noun accusative singular feminine", "l": "ἀνάγκη"},
                    {"h": "τὸ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular neuter", "l": "ὁ"},
                    {"h": "ἀγαθόν", "t": "agathós", "s": "G18", "g": "benefit", "m": "adjective nominative singular neuter", "l": "ἀγαθός"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ᾖ", "t": "eimí", "s": "G1510", "g": "am", "m": "verb 3rd present active subjunctive singular", "l": "εἰμί"},
                    {"h": "ἀλλὰ", "t": "allá", "s": "G235", "g": "and", "m": "conjunction", "l": "ἀλλά"},
                    {"h": "κατὰ", "t": "katá", "s": "G2596", "g": "about", "m": "preposition", "l": "κατά"},
                    {"h": "ἑκούσιον", "m": "adjective accusative singular neuter", "l": "ἑκούσιος"},
                ]
            },
            {
                "num": 15,
                "words": [
                    {"h": "τάχα", "t": "tácha", "s": "G5029", "g": "peradventure", "m": "adverb"},
                    {"h": "γὰρ", "t": "gár", "s": "G1063", "g": "and", "m": "conjunction", "l": "γάρ"},
                    {"h": "διὰ", "t": "diá", "s": "G1223", "g": "after", "m": "preposition", "l": "διά"},
                    {"h": "τοῦτο", "t": "hoûtos", "s": "G3778", "g": "he", "m": "demonstrative accusative singular neuter", "l": "οὗτος"},
                    {"h": "ἐχωρίσθη", "t": "chōrízō", "s": "G5563", "g": "depart", "m": "verb 3rd aorist passive indicative singular", "l": "χωρίζω"},
                    {"h": "πρὸς", "t": "prós", "s": "G4314", "g": "about", "m": "preposition", "l": "πρός"},
                    {"h": "ὥραν", "t": "hṓra", "s": "G5610", "g": "day", "m": "noun accusative singular feminine", "l": "ὥρα"},
                    {"h": "ἵνα", "t": "hína", "s": "G2443", "g": "albeit", "m": "conjunction"},
                    {"h": "αἰώνιον", "t": "aiṓnios", "s": "G166", "g": "eternal", "m": "adjective accusative singular masculine", "l": "αἰώνιος"},
                    {"h": "αὐτὸν", "t": "autós", "s": "G846", "g": "her", "m": "personal pronoun accusative singular masculine", "l": "αὐτός"},
                    {"h": "ἀπέχῃς", "t": "apéchō", "s": "G568", "g": "be", "m": "verb 2nd aorist active subjunctive singular", "l": "ἀπέχω"},
                ]
            },
            {
                "num": 16,
                "words": [
                    {"h": "οὐκέτι", "t": "oukéti", "s": "G3765", "g": "after that", "m": "adverb"},
                    {"h": "ὡς", "t": "hōs", "s": "G5613", "g": "about", "m": "conjunction"},
                    {"h": "δοῦλον", "t": "doûlos", "s": "G1401", "g": "bond", "m": "noun accusative singular masculine", "l": "δοῦλος"},
                    {"h": "ἀλλὰ", "t": "allá", "s": "G235", "g": "and", "m": "conjunction", "l": "ἀλλά"},
                    {"h": "ὑπὲρ", "t": "hypér", "s": "G5228", "g": "(+ exceeding", "m": "preposition", "l": "ὑπέρ"},
                    {"h": "δοῦλον", "t": "doûlos", "s": "G1401", "g": "bond", "m": "noun accusative singular masculine", "l": "δοῦλος"},
                    {"h": "ἀδελφὸν", "t": "adelphós", "s": "G80", "g": "brother", "m": "noun accusative singular masculine", "l": "ἀδελφός"},
                    {"h": "ἀγαπητόν", "t": "agapētós", "s": "G27", "g": "(dearly", "m": "adjective accusative singular masculine", "l": "ἀγαπητός"},
                    {"h": "μάλιστα", "t": "málista", "s": "G3122", "g": "chiefly", "m": "adverb"},
                    {"h": "ἐμοί", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun dative singular", "l": "ἐγώ"},
                    {"h": "πόσῳ", "t": "pósos", "s": "G4214", "g": "how great (long", "m": "interrogative dative singular neuter", "l": "πόσος"},
                    {"h": "δὲ", "t": "dé", "s": "G1161", "g": "also", "m": "conjunction", "l": "δέ"},
                    {"h": "μᾶλλον", "t": "mâllon", "s": "G3123", "g": "+ better", "m": "adverb"},
                    {"h": "σοὶ", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "σαρκὶ", "t": "sárx", "s": "G4561", "g": "carnal(-ly", "m": "noun dative singular feminine", "l": "σάρξ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "κυρίῳ", "t": "kýrios", "s": "G2962", "g": "God", "m": "noun dative singular masculine", "l": "κύριος"},
                ]
            },
            {
                "num": 17,
                "words": [
                    {"h": "Εἰ", "t": "eî", "s": "G1488", "g": "art", "m": "conjunction", "l": "εἰ"},
                    {"h": "οὖν", "t": "oûn", "s": "G3767", "g": "and (so", "m": "conjunction"},
                    {"h": "με", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun accusative singular", "l": "ἐγώ"},
                    {"h": "ἔχεις", "t": "échō", "s": "G2192", "g": "be (able", "m": "verb 2nd present active indicative singular", "l": "ἔχω"},
                    {"h": "κοινωνόν", "t": "koinōnós", "s": "G2844", "g": "companion", "m": "noun accusative singular masculine", "l": "κοινωνός"},
                    {"h": "προσλαβοῦ", "m": "verb 2nd aorist middle imperative singular", "l": "προσλαμβάνομαι"},
                    {"h": "αὐτὸν", "t": "autós", "s": "G846", "g": "her", "m": "personal pronoun accusative singular masculine", "l": "αὐτός"},
                    {"h": "ὡς", "t": "hōs", "s": "G5613", "g": "about", "m": "conjunction"},
                    {"h": "ἐμέ", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun accusative singular", "l": "ἐγώ"},
                ]
            },
            {
                "num": 18,
                "words": [
                    {"h": "εἰ", "t": "eî", "s": "G1488", "g": "art", "m": "conjunction"},
                    {"h": "δέ", "t": "dé", "s": "G1161", "g": "also", "m": "conjunction"},
                    {"h": "τι", "t": "tìs", "s": "G5100", "g": "a", "m": "interrogative accusative singular neuter", "l": "τις"},
                    {"h": "ἠδίκησέν", "t": "adikéō", "s": "G91", "g": "hurt", "m": "verb 3rd aorist active indicative singular", "l": "ἀδικέω"},
                    {"h": "σε", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun accusative singular", "l": "σύ"},
                    {"h": "ἢ", "t": "ē", "s": "G2229", "g": "surely", "m": "conjunction", "l": "ἤ"},
                    {"h": "ὀφείλει", "t": "opheílō", "s": "G3784", "g": "behove", "m": "verb 3rd present active indicative singular", "l": "ὀφείλω"},
                    {"h": "τοῦτο", "t": "hoûtos", "s": "G3778", "g": "he", "m": "demonstrative accusative singular neuter", "l": "οὗτος"},
                    {"h": "ἐμοὶ", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun dative singular", "l": "ἐγώ"},
                    {"h": "⸀ἐλλόγα", "t": "ellogéō", "s": "G1677", "g": "impute", "m": "verb 2nd present active imperative singular", "l": "ἐλλογέω"},
                ]
            },
            {
                "num": 19,
                "words": [
                    {"h": "ἐγὼ", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun nominative singular", "l": "ἐγώ"},
                    {"h": "Παῦλος", "t": "Paûlos", "s": "G3972", "g": "Paul", "m": "noun nominative singular masculine"},
                    {"h": "ἔγραψα", "t": "gráphō", "s": "G1125", "g": "describe", "m": "verb 1st aorist active indicative singular", "l": "γράφω"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "ἐμῇ", "t": "emós", "s": "G1699", "g": "of me", "m": "adjective dative singular feminine", "l": "ἐμός"},
                    {"h": "χειρί", "t": "cheír", "s": "G5495", "g": "hand", "m": "noun dative singular feminine", "l": "χείρ"},
                    {"h": "ἐγὼ", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun nominative singular", "l": "ἐγώ"},
                    {"h": "ἀποτίσω", "t": "apotínō", "s": "G661", "g": "repay", "m": "verb 1st future active indicative singular", "l": "ἀποτίνω"},
                    {"h": "ἵνα", "t": "hína", "s": "G2443", "g": "albeit", "m": "conjunction"},
                    {"h": "μὴ", "t": "mḗ", "s": "G3361", "g": "any but", "m": "adverb", "l": "μή"},
                    {"h": "λέγω", "t": "légō", "s": "G3004", "g": "ask", "m": "verb 1st present active subjunctive singular"},
                    {"h": "σοι", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "ὅτι", "t": "hóti", "s": "G3754", "g": "as concerning that", "m": "conjunction"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "adverb", "l": "καί"},
                    {"h": "σεαυτόν", "t": "seautoû", "s": "G4572", "g": "thee", "m": "personal pronoun accusative singular masculine", "l": "σεαυτοῦ"},
                    {"h": "μοι", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun dative singular", "l": "ἐγώ"},
                    {"h": "προσοφείλεις", "t": "prosopheílō", "s": "G4359", "g": "over besides", "m": "verb 2nd present active indicative singular", "l": "προσοφείλω"},
                ]
            },
            {
                "num": 20,
                "words": [
                    {"h": "ναί", "t": "naí", "s": "G3483", "g": "even so", "m": "particle"},
                    {"h": "ἀδελφέ", "t": "adelphós", "s": "G80", "g": "brother", "m": "noun singular masculine", "l": "ἀδελφός"},
                    {"h": "ἐγώ", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun nominative singular"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ὀναίμην", "t": "onínēmi", "s": "G3685", "g": "have joy", "m": "verb 1st aorist middle optative singular", "l": "ὀνίνημι"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "κυρίῳ", "t": "kýrios", "s": "G2962", "g": "God", "m": "noun dative singular masculine", "l": "κύριος"},
                    {"h": "ἀνάπαυσόν", "t": "anapaúō", "s": "G373", "g": "take ease", "m": "verb 2nd aorist active imperative singular", "l": "ἀναπαύω"},
                    {"h": "μου", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive singular", "l": "ἐγώ"},
                    {"h": "τὰ", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural neuter", "l": "ὁ"},
                    {"h": "σπλάγχνα", "t": "splánchnon", "s": "G4698", "g": "bowels", "m": "noun accusative plural neuter", "l": "σπλάγχνον"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "⸀Χριστῷ", "t": "Christós", "s": "G5547", "g": "Christ", "m": "noun dative singular masculine", "l": "Χριστός"},
                ]
            },
            {
                "num": 21,
                "words": [
                    {"h": "πεποιθὼς", "t": "peíthō", "s": "G3982", "g": "agree", "m": "verb perfect active participle nominative singular masculine", "l": "πείθω"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "ὑπακοῇ", "t": "hypakoḗ", "s": "G5218", "g": "obedience", "m": "noun dative singular feminine", "l": "ὑπακοή"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ἔγραψά", "t": "gráphō", "s": "G1125", "g": "describe", "m": "verb 1st aorist active indicative singular", "l": "γράφω"},
                    {"h": "σοι", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "εἰδὼς", "t": "horáō", "s": "G3708", "g": "behold", "m": "verb perfect active participle nominative singular masculine", "l": "ὁράω"},
                    {"h": "ὅτι", "t": "hóti", "s": "G3754", "g": "as concerning that", "m": "conjunction"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "adverb", "l": "καί"},
                    {"h": "ὑπὲρ", "t": "hypér", "s": "G5228", "g": "(+ exceeding", "m": "preposition", "l": "ὑπέρ"},
                    {"h": "⸀ἃ", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative plural neuter", "l": "ὅς"},
                    {"h": "λέγω", "t": "légō", "s": "G3004", "g": "ask", "m": "verb 1st present active indicative singular"},
                    {"h": "ποιήσεις", "t": "poiéō", "s": "G4160", "g": "abide", "m": "verb 2nd future active indicative singular", "l": "ποιέω"},
                ]
            },
            {
                "num": 22,
                "words": [
                    {"h": "ἅμα", "t": "háma", "s": "G260", "g": "also", "m": "adverb"},
                    {"h": "δὲ", "t": "dé", "s": "G1161", "g": "also", "m": "conjunction", "l": "δέ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "adverb", "l": "καί"},
                    {"h": "ἑτοίμαζέ", "t": "hetoimázō", "s": "G2090", "g": "prepare", "m": "verb 2nd present active imperative singular", "l": "ἑτοιμάζω"},
                    {"h": "μοι", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun dative singular", "l": "ἐγώ"},
                    {"h": "ξενίαν", "t": "xenía", "s": "G3578", "g": "lodging", "m": "noun accusative singular feminine", "l": "ξενία"},
                    {"h": "ἐλπίζω", "t": "elpízō", "s": "G1679", "g": "(have", "m": "verb 1st present active indicative singular"},
                    {"h": "γὰρ", "t": "gár", "s": "G1063", "g": "and", "m": "conjunction", "l": "γάρ"},
                    {"h": "ὅτι", "t": "hóti", "s": "G3754", "g": "as concerning that", "m": "conjunction"},
                    {"h": "διὰ", "t": "diá", "s": "G1223", "g": "after", "m": "preposition", "l": "διά"},
                    {"h": "τῶν", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive plural feminine", "l": "ὁ"},
                    {"h": "προσευχῶν", "t": "proseuchḗ", "s": "G4335", "g": "X pray earnestly", "m": "noun genitive plural feminine", "l": "προσευχή"},
                    {"h": "ὑμῶν", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive plural", "l": "σύ"},
                    {"h": "χαρισθήσομαι", "t": "charízomai", "s": "G5483", "g": "deliver", "m": "verb 1st future passive indicative singular", "l": "χαρίζομαι"},
                    {"h": "ὑμῖν", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative plural", "l": "σύ"},
                ]
            },
            {
                "num": 23,
                "words": [
                    {"h": "⸀Ἀσπάζεταί", "t": "aspázomai", "s": "G782", "g": "embrace", "m": "verb 3rd present middle indicative singular", "l": "ἀσπάζομαι"},
                    {"h": "σε", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun accusative singular", "l": "σύ"},
                    {"h": "Ἐπαφρᾶς", "t": "Epaphrâs", "s": "G1889", "g": "Epaphras", "m": "noun nominative singular masculine"},
                    {"h": "ὁ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular masculine"},
                    {"h": "συναιχμάλωτός", "t": "synaichmálōtos", "s": "G4869", "g": "fellowprisoner", "m": "noun nominative singular masculine", "l": "συναιχμάλωτος"},
                    {"h": "μου", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive singular", "l": "ἐγώ"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "Χριστῷ", "t": "Christós", "s": "G5547", "g": "Christ", "m": "noun dative singular masculine", "l": "Χριστός"},
                    {"h": "Ἰησοῦ", "t": "Iēsoûs", "s": "G2424", "g": "Jesus", "m": "noun dative singular masculine", "l": "Ἰησοῦς"},
                ]
            },
            {
                "num": 24,
                "words": [
                    {"h": "Μᾶρκος", "t": "Márkos", "s": "G3138", "g": "Marcus", "m": "noun nominative singular masculine"},
                    {"h": "Ἀρίσταρχος", "t": "Arístarchos", "s": "G708", "g": "Aristarchus", "m": "noun nominative singular masculine"},
                    {"h": "Δημᾶς", "t": "Dēmâs", "s": "G1214", "g": "Demas", "m": "noun nominative singular masculine"},
                    {"h": "Λουκᾶς", "t": "Loukâs", "s": "G3065", "g": "Lucas", "m": "noun nominative singular masculine"},
                    {"h": "οἱ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative plural masculine", "l": "ὁ"},
                    {"h": "συνεργοί", "t": "synergós", "s": "G4904", "g": "companion in labour", "m": "adjective nominative plural masculine", "l": "συνεργός"},
                    {"h": "μου", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive singular", "l": "ἐγώ"},
                ]
            },
            {
                "num": 25,
                "words": [
                    {"h": "Ἡ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular feminine", "l": "ὁ"},
                    {"h": "χάρις", "t": "cháris", "s": "G5485", "g": "acceptable", "m": "noun nominative singular feminine"},
                    {"h": "τοῦ", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular masculine", "l": "ὁ"},
                    {"h": "⸀κυρίου", "t": "kýrios", "s": "G2962", "g": "God", "m": "noun genitive singular masculine", "l": "κύριος"},
                    {"h": "Ἰησοῦ", "t": "Iēsoûs", "s": "G2424", "g": "Jesus", "m": "noun genitive singular masculine", "l": "Ἰησοῦς"},
                    {"h": "Χριστοῦ", "t": "Christós", "s": "G5547", "g": "Christ", "m": "noun genitive singular masculine", "l": "Χριστός"},
                    {"h": "μετὰ", "t": "metá", "s": "G3326", "g": "after", "m": "preposition", "l": "μετά"},
                    {"h": "τοῦ", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular neuter", "l": "ὁ"},
                    {"h": "πνεύματος", "t": "pneûma", "s": "G4151", "g": "ghost", "m": "noun genitive singular neuter", "l": "πνεῦμα"},
                    {"h": "⸀ὑμῶν", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive plural", "l": "σύ"},
                ]
            },
        ]
    },
}
