"""
Auto-generated interlinear Greek-English data for 3 John.

Source: MorphGNT SBLGNT (https://github.com/morphgnt/sblgnt) — CC-BY-SA 3.0
        Strong's Greek Dictionary (openscriptures) — CC-BY 4.0

Generated by build_nt_interlinear.py

Keys:  h = Greek text (with accents) — same slot as Hebrew "h"
       t = transliteration
       s = Strong's G-number
       g = English gloss — same slot as Hebrew "g"
       m = morphology
       l = lexical lemma
"""

INTERLINEAR_NT_3JOHN = {
    1: {
        "verses": [
            {
                "num": 1,
                "words": [
                    {"h": "Ὁ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular masculine", "l": "ὁ"},
                    {"h": "πρεσβύτερος", "t": "presbýteros", "s": "G4245", "g": "elder", "m": "adjective nominative singular masculine"},
                    {"h": "Γαΐῳ", "t": "Gáïos", "s": "G1050", "g": "Gaius", "m": "noun dative singular masculine", "l": "Γάϊος"},
                    {"h": "τῷ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular masculine", "l": "ὁ"},
                    {"h": "ἀγαπητῷ", "t": "agapētós", "s": "G27", "g": "(dearly", "m": "adjective dative singular masculine", "l": "ἀγαπητός"},
                    {"h": "ὃν", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative singular masculine", "l": "ὅς"},
                    {"h": "ἐγὼ", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun nominative singular", "l": "ἐγώ"},
                    {"h": "ἀγαπῶ", "t": "agapáō", "s": "G25", "g": "love", "m": "verb 1st present active indicative singular", "l": "ἀγαπάω"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "ἀληθείᾳ", "t": "alḗtheia", "s": "G225", "g": "true", "m": "noun dative singular feminine", "l": "ἀλήθεια"},
                ]
            },
            {
                "num": 2,
                "words": [
                    {"h": "Ἀγαπητέ", "t": "agapētós", "s": "G27", "g": "(dearly", "m": "adjective singular masculine", "l": "ἀγαπητός"},
                    {"h": "περὶ", "t": "perí", "s": "G4012", "g": "about", "m": "preposition", "l": "περί"},
                    {"h": "πάντων", "t": "pâs", "s": "G3956", "g": "all (manner of", "m": "adjective genitive plural neuter", "l": "πᾶς"},
                    {"h": "εὔχομαί", "t": "eúchomai", "s": "G2172", "g": "pray", "m": "verb 1st present middle indicative singular", "l": "εὔχομαι"},
                    {"h": "σε", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun accusative singular", "l": "σύ"},
                    {"h": "εὐοδοῦσθαι", "m": "verb present passive infinitive", "l": "εὐοδόομαι"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "ὑγιαίνειν", "t": "hygiaínō", "s": "G5198", "g": "be in health", "m": "verb present active infinitive", "l": "ὑγιαίνω"},
                    {"h": "καθὼς", "t": "kathṓs", "s": "G2531", "g": "according to", "m": "conjunction", "l": "καθώς"},
                    {"h": "εὐοδοῦταί", "m": "verb 3rd present passive indicative singular", "l": "εὐοδόομαι"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "ἡ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular feminine", "l": "ὁ"},
                    {"h": "ψυχή", "t": "psychḗ", "s": "G5590", "g": "heart", "m": "noun nominative singular feminine"},
                ]
            },
            {
                "num": 3,
                "words": [
                    {"h": "ἐχάρην", "t": "chaírō", "s": "G5463", "g": "farewell", "m": "verb 1st aorist passive indicative singular", "l": "χαίρω"},
                    {"h": "γὰρ", "t": "gár", "s": "G1063", "g": "and", "m": "conjunction", "l": "γάρ"},
                    {"h": "λίαν", "t": "lían", "s": "G3029", "g": "exceeding", "m": "adverb"},
                    {"h": "ἐρχομένων", "t": "érchomai", "s": "G2064", "g": "accompany", "m": "verb present middle participle genitive plural masculine", "l": "ἔρχομαι"},
                    {"h": "ἀδελφῶν", "t": "adelphós", "s": "G80", "g": "brother", "m": "noun genitive plural masculine", "l": "ἀδελφός"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "μαρτυρούντων", "t": "martyréō", "s": "G3140", "g": "charge", "m": "verb present active participle genitive plural masculine", "l": "μαρτυρέω"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "ἀληθείᾳ", "t": "alḗtheia", "s": "G225", "g": "true", "m": "noun dative singular feminine", "l": "ἀλήθεια"},
                    {"h": "καθὼς", "t": "kathṓs", "s": "G2531", "g": "according to", "m": "conjunction", "l": "καθώς"},
                    {"h": "σὺ", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun nominative singular", "l": "σύ"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "ἀληθείᾳ", "t": "alḗtheia", "s": "G225", "g": "true", "m": "noun dative singular feminine", "l": "ἀλήθεια"},
                    {"h": "περιπατεῖς", "t": "peripatéō", "s": "G4043", "g": "go", "m": "verb 2nd present active indicative singular", "l": "περιπατέω"},
                ]
            },
            {
                "num": 4,
                "words": [
                    {"h": "μειζοτέραν", "t": "meizóteros", "s": "G3186", "g": "greater", "m": "adjective accusative singular feminine comparative", "l": "μειζότερος"},
                    {"h": "τούτων", "t": "hoûtos", "s": "G3778", "g": "he", "m": "demonstrative genitive plural neuter", "l": "οὗτος"},
                    {"h": "οὐκ", "t": "ou", "s": "G3756", "g": "+ long", "m": "adverb", "l": "οὐ"},
                    {"h": "ἔχω", "t": "échō", "s": "G2192", "g": "be (able", "m": "verb 1st present active indicative singular"},
                    {"h": "⸀χαράν", "t": "chará", "s": "G5479", "g": "gladness", "m": "noun accusative singular feminine", "l": "χαρά"},
                    {"h": "ἵνα", "t": "hína", "s": "G2443", "g": "albeit", "m": "adverb"},
                    {"h": "ἀκούω", "t": "akoúō", "s": "G191", "g": "give  audience", "m": "verb 1st present active subjunctive singular"},
                    {"h": "τὰ", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural neuter", "l": "ὁ"},
                    {"h": "ἐμὰ", "t": "emós", "s": "G1699", "g": "of me", "m": "adjective accusative plural neuter", "l": "ἐμός"},
                    {"h": "τέκνα", "t": "téknon", "s": "G5043", "g": "child", "m": "noun accusative plural neuter", "l": "τέκνον"},
                    {"h": "ἐν", "t": "en", "s": "G1722", "g": "about", "m": "preposition"},
                    {"h": "⸀τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "ἀληθείᾳ", "t": "alḗtheia", "s": "G225", "g": "true", "m": "noun dative singular feminine", "l": "ἀλήθεια"},
                    {"h": "περιπατοῦντα", "t": "peripatéō", "s": "G4043", "g": "go", "m": "verb present active participle accusative plural neuter", "l": "περιπατέω"},
                ]
            },
            {
                "num": 5,
                "words": [
                    {"h": "Ἀγαπητέ", "t": "agapētós", "s": "G27", "g": "(dearly", "m": "adjective singular masculine", "l": "ἀγαπητός"},
                    {"h": "πιστὸν", "t": "pistós", "s": "G4103", "g": "believe(-ing", "m": "adjective accusative singular neuter", "l": "πιστός"},
                    {"h": "ποιεῖς", "t": "poiéō", "s": "G4160", "g": "abide", "m": "verb 2nd present active indicative singular", "l": "ποιέω"},
                    {"h": "ὃ", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative singular neuter", "l": "ὅς"},
                    {"h": "ἐὰν", "t": "eán", "s": "G1437", "g": "before", "m": "particle", "l": "ἐάν"},
                    {"h": "ἐργάσῃ", "t": "ergázomai", "s": "G2038", "g": "commit", "m": "verb 2nd aorist middle subjunctive singular", "l": "ἐργάζομαι"},
                    {"h": "εἰς", "t": "heîs", "s": "G1520", "g": "a(-n", "m": "preposition"},
                    {"h": "τοὺς", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural masculine", "l": "ὁ"},
                    {"h": "ἀδελφοὺς", "t": "adelphós", "s": "G80", "g": "brother", "m": "noun accusative plural masculine", "l": "ἀδελφός"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "⸀τοῦτο", "t": "hoûtos", "s": "G3778", "g": "he", "m": "demonstrative accusative singular neuter", "l": "οὗτος"},
                    {"h": "ξένους", "t": "xénos", "s": "G3581", "g": "host", "m": "adjective accusative plural masculine", "l": "ξένος"},
                ]
            },
            {
                "num": 6,
                "words": [
                    {"h": "οἳ", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun nominative plural masculine", "l": "ὅς"},
                    {"h": "ἐμαρτύρησάν", "t": "martyréō", "s": "G3140", "g": "charge", "m": "verb 3rd aorist active indicative plural", "l": "μαρτυρέω"},
                    {"h": "σου", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun genitive singular", "l": "σύ"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "ἀγάπῃ", "t": "agápē", "s": "G26", "g": "charity", "m": "noun dative singular feminine", "l": "ἀγάπη"},
                    {"h": "ἐνώπιον", "t": "enṓpion", "s": "G1799", "g": "before", "m": "preposition"},
                    {"h": "ἐκκλησίας", "t": "ekklēsía", "s": "G1577", "g": "assembly", "m": "noun genitive singular feminine", "l": "ἐκκλησία"},
                    {"h": "οὓς", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative plural masculine", "l": "ὅς"},
                    {"h": "καλῶς", "t": "kalōs", "s": "G2573", "g": "good", "m": "adverb"},
                    {"h": "ποιήσεις", "t": "poiéō", "s": "G4160", "g": "abide", "m": "verb 2nd future active indicative singular", "l": "ποιέω"},
                    {"h": "προπέμψας", "t": "propémpō", "s": "G4311", "g": "accompany", "m": "verb aorist active participle nominative singular masculine", "l": "προπέμπω"},
                    {"h": "ἀξίως", "t": "axíōs", "s": "G516", "g": "as becometh", "m": "adverb"},
                    {"h": "τοῦ", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular masculine", "l": "ὁ"},
                    {"h": "θεοῦ", "t": "theós", "s": "G2316", "g": "X exceeding", "m": "noun genitive singular masculine", "l": "θεός"},
                ]
            },
            {
                "num": 7,
                "words": [
                    {"h": "ὑπὲρ", "t": "hypér", "s": "G5228", "g": "(+ exceeding", "m": "preposition", "l": "ὑπέρ"},
                    {"h": "γὰρ", "t": "gár", "s": "G1063", "g": "and", "m": "conjunction", "l": "γάρ"},
                    {"h": "τοῦ", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular neuter", "l": "ὁ"},
                    {"h": "ὀνόματος", "t": "ónoma", "s": "G3686", "g": "called", "m": "noun genitive singular neuter", "l": "ὄνομα"},
                    {"h": "ἐξῆλθον", "t": "exérchomai", "s": "G1831", "g": "come (forth", "m": "verb 3rd aorist active indicative plural", "l": "ἐξέρχομαι"},
                    {"h": "μηδὲν", "t": "mēdeís", "s": "G3367", "g": "any (man", "m": "adjective accusative singular neuter", "l": "μηδείς"},
                    {"h": "λαμβάνοντες", "t": "lambánō", "s": "G2983", "g": "accept", "m": "verb present active participle nominative plural masculine", "l": "λαμβάνω"},
                    {"h": "ἀπὸ", "t": "apó", "s": "G575", "g": "after", "m": "preposition", "l": "ἀπό"},
                    {"h": "τῶν", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive plural masculine", "l": "ὁ"},
                    {"h": "⸀ἐθνικῶν", "t": "ethnikós", "s": "G1482", "g": "heathen", "m": "adjective genitive plural masculine", "l": "ἐθνικός"},
                ]
            },
            {
                "num": 8,
                "words": [
                    {"h": "ἡμεῖς", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun nominative plural", "l": "ἐγώ"},
                    {"h": "οὖν", "t": "oûn", "s": "G3767", "g": "and (so", "m": "conjunction"},
                    {"h": "ὀφείλομεν", "t": "opheílō", "s": "G3784", "g": "behove", "m": "verb 1st present active indicative plural", "l": "ὀφείλω"},
                    {"h": "⸀ὑπολαμβάνειν", "t": "hypolambánō", "s": "G5274", "g": "answer", "m": "verb present active infinitive", "l": "ὑπολαμβάνω"},
                    {"h": "τοὺς", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural masculine", "l": "ὁ"},
                    {"h": "τοιούτους", "t": "toioûtos", "s": "G5108", "g": "like", "m": "demonstrative accusative plural masculine", "l": "τοιοῦτος"},
                    {"h": "ἵνα", "t": "hína", "s": "G2443", "g": "albeit", "m": "conjunction"},
                    {"h": "συνεργοὶ", "t": "synergós", "s": "G4904", "g": "companion in labour", "m": "adjective nominative plural masculine", "l": "συνεργός"},
                    {"h": "γινώμεθα", "t": "gínomai", "s": "G1096", "g": "arise", "m": "verb 1st present middle subjunctive plural", "l": "γίνομαι"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "ἀληθείᾳ", "t": "alḗtheia", "s": "G225", "g": "true", "m": "noun dative singular feminine", "l": "ἀλήθεια"},
                ]
            },
            {
                "num": 9,
                "words": [
                    {"h": "Ἔγραψά", "t": "gráphō", "s": "G1125", "g": "describe", "m": "verb 1st aorist active indicative singular", "l": "γράφω"},
                    {"h": "⸀τι", "t": "tìs", "s": "G5100", "g": "a", "m": "interrogative accusative singular neuter", "l": "τις"},
                    {"h": "τῇ", "t": "ho", "s": "G3588", "g": "the", "m": "article dative singular feminine", "l": "ὁ"},
                    {"h": "ἐκκλησίᾳ", "t": "ekklēsía", "s": "G1577", "g": "assembly", "m": "noun dative singular feminine", "l": "ἐκκλησία"},
                    {"h": "ἀλλ’", "t": "allá", "s": "G235", "g": "and", "m": "conjunction", "l": "ἀλλά"},
                    {"h": "ὁ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular masculine"},
                    {"h": "φιλοπρωτεύων", "t": "philoprōteúō", "s": "G5383", "g": "love to have the preeminence", "m": "verb present active participle nominative singular masculine", "l": "φιλοπρωτεύω"},
                    {"h": "αὐτῶν", "t": "autós", "s": "G846", "g": "her", "m": "personal pronoun genitive plural masculine", "l": "αὐτός"},
                    {"h": "Διοτρέφης", "t": "Diotrephḗs", "s": "G1361", "g": "Diotrephes", "m": "noun nominative singular masculine"},
                    {"h": "οὐκ", "t": "ou", "s": "G3756", "g": "+ long", "m": "adverb", "l": "οὐ"},
                    {"h": "ἐπιδέχεται", "t": "epidéchomai", "s": "G1926", "g": "receive", "m": "verb 3rd present middle indicative singular", "l": "ἐπιδέχομαι"},
                    {"h": "ἡμᾶς", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun accusative plural", "l": "ἐγώ"},
                ]
            },
            {
                "num": 10,
                "words": [
                    {"h": "διὰ", "t": "diá", "s": "G1223", "g": "after", "m": "preposition", "l": "διά"},
                    {"h": "τοῦτο", "t": "hoûtos", "s": "G3778", "g": "he", "m": "demonstrative accusative singular neuter", "l": "οὗτος"},
                    {"h": "ἐὰν", "t": "eán", "s": "G1437", "g": "before", "m": "conjunction", "l": "ἐάν"},
                    {"h": "ἔλθω", "t": "érchomai", "s": "G2064", "g": "accompany", "m": "verb 1st aorist active subjunctive singular", "l": "ἔρχομαι"},
                    {"h": "ὑπομνήσω", "t": "hypomimnḗskō", "s": "G5279", "g": "put in mind", "m": "verb 1st future active indicative singular", "l": "ὑπομιμνῄσκω"},
                    {"h": "αὐτοῦ", "t": "autós", "s": "G846", "g": "her", "m": "personal pronoun genitive singular masculine", "l": "αὐτός"},
                    {"h": "τὰ", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural neuter", "l": "ὁ"},
                    {"h": "ἔργα", "t": "érgon", "s": "G2041", "g": "deed", "m": "noun accusative plural neuter", "l": "ἔργον"},
                    {"h": "ἃ", "t": "hós", "s": "G3739", "g": "one", "m": "relative pronoun accusative plural neuter", "l": "ὅς"},
                    {"h": "ποιεῖ", "t": "poiéō", "s": "G4160", "g": "abide", "m": "verb 3rd present active indicative singular", "l": "ποιέω"},
                    {"h": "λόγοις", "t": "lógos", "s": "G3056", "g": "account", "m": "noun dative plural masculine", "l": "λόγος"},
                    {"h": "πονηροῖς", "t": "ponērós", "s": "G4190", "g": "bad", "m": "adjective dative plural masculine", "l": "πονηρός"},
                    {"h": "φλυαρῶν", "t": "phlyaréō", "s": "G5396", "g": "prate against", "m": "verb present active participle nominative singular masculine", "l": "φλυαρέω"},
                    {"h": "ἡμᾶς", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun accusative plural", "l": "ἐγώ"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "μὴ", "t": "mḗ", "s": "G3361", "g": "any but", "m": "adverb", "l": "μή"},
                    {"h": "ἀρκούμενος", "t": "arkéō", "s": "G714", "g": "be content", "m": "verb present passive participle nominative singular masculine", "l": "ἀρκέω"},
                    {"h": "ἐπὶ", "t": "epí", "s": "G1909", "g": "about", "m": "preposition", "l": "ἐπί"},
                    {"h": "τούτοις", "t": "hoûtos", "s": "G3778", "g": "he", "m": "demonstrative dative plural neuter", "l": "οὗτος"},
                    {"h": "οὔτε", "t": "oúte", "s": "G3777", "g": "neither", "m": "conjunction"},
                    {"h": "αὐτὸς", "t": "autós", "s": "G846", "g": "her", "m": "personal pronoun nominative singular masculine", "l": "αὐτός"},
                    {"h": "ἐπιδέχεται", "t": "epidéchomai", "s": "G1926", "g": "receive", "m": "verb 3rd present middle indicative singular", "l": "ἐπιδέχομαι"},
                    {"h": "τοὺς", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural masculine", "l": "ὁ"},
                    {"h": "ἀδελφοὺς", "t": "adelphós", "s": "G80", "g": "brother", "m": "noun accusative plural masculine", "l": "ἀδελφός"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "τοὺς", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural masculine", "l": "ὁ"},
                    {"h": "βουλομένους", "t": "boúlomai", "s": "G1014", "g": "be disposed", "m": "verb present middle participle accusative plural masculine", "l": "βούλομαι"},
                    {"h": "κωλύει", "t": "kōlýō", "s": "G2967", "g": "forbid", "m": "verb 3rd present active indicative singular", "l": "κωλύω"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "ἐκ", "t": "ek", "s": "G1537", "g": "after", "m": "preposition"},
                    {"h": "τῆς", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular feminine", "l": "ὁ"},
                    {"h": "ἐκκλησίας", "t": "ekklēsía", "s": "G1577", "g": "assembly", "m": "noun genitive singular feminine", "l": "ἐκκλησία"},
                    {"h": "ἐκβάλλει", "t": "ekbállō", "s": "G1544", "g": "bring forth", "m": "verb 3rd present active indicative singular", "l": "ἐκβάλλω"},
                ]
            },
            {
                "num": 11,
                "words": [
                    {"h": "Ἀγαπητέ", "t": "agapētós", "s": "G27", "g": "(dearly", "m": "adjective singular masculine", "l": "ἀγαπητός"},
                    {"h": "μὴ", "t": "mḗ", "s": "G3361", "g": "any but", "m": "adverb", "l": "μή"},
                    {"h": "μιμοῦ", "t": "miméomai", "s": "G3401", "g": "follow", "m": "verb 2nd present middle imperative singular", "l": "μιμέομαι"},
                    {"h": "τὸ", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular neuter", "l": "ὁ"},
                    {"h": "κακὸν", "t": "kakós", "s": "G2556", "g": "bad", "m": "adjective accusative singular neuter", "l": "κακός"},
                    {"h": "ἀλλὰ", "t": "allá", "s": "G235", "g": "and", "m": "conjunction", "l": "ἀλλά"},
                    {"h": "τὸ", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular neuter", "l": "ὁ"},
                    {"h": "ἀγαθόν", "t": "agathós", "s": "G18", "g": "benefit", "m": "adjective accusative singular neuter", "l": "ἀγαθός"},
                    {"h": "ὁ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular masculine"},
                    {"h": "ἀγαθοποιῶν", "t": "agathopoiéō", "s": "G15", "g": "do good", "m": "verb present active participle nominative singular masculine", "l": "ἀγαθοποιέω"},
                    {"h": "ἐκ", "t": "ek", "s": "G1537", "g": "after", "m": "preposition"},
                    {"h": "τοῦ", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular masculine", "l": "ὁ"},
                    {"h": "θεοῦ", "t": "theós", "s": "G2316", "g": "X exceeding", "m": "noun genitive singular masculine", "l": "θεός"},
                    {"h": "ἐστιν", "t": "eimí", "s": "G1510", "g": "am", "m": "verb 3rd present active indicative singular", "l": "εἰμί"},
                    {"h": "ὁ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular masculine"},
                    {"h": "κακοποιῶν", "t": "kakopoiéō", "s": "G2554", "g": "do evil", "m": "verb present active participle nominative singular masculine", "l": "κακοποιέω"},
                    {"h": "οὐχ", "t": "ou", "s": "G3756", "g": "+ long", "m": "adverb", "l": "οὐ"},
                    {"h": "ἑώρακεν", "t": "horáō", "s": "G3708", "g": "behold", "m": "verb 3rd perfect active indicative singular", "l": "ὁράω"},
                    {"h": "τὸν", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative singular masculine", "l": "ὁ"},
                    {"h": "θεόν", "t": "theós", "s": "G2316", "g": "X exceeding", "m": "noun accusative singular masculine", "l": "θεός"},
                ]
            },
            {
                "num": 12,
                "words": [
                    {"h": "Δημητρίῳ", "t": "Dēmḗtrios", "s": "G1216", "g": "Demetrius", "m": "noun dative singular masculine", "l": "Δημήτριος"},
                    {"h": "μεμαρτύρηται", "t": "martyréō", "s": "G3140", "g": "charge", "m": "verb 3rd perfect passive indicative singular", "l": "μαρτυρέω"},
                    {"h": "ὑπὸ", "t": "hypó", "s": "G5259", "g": "among", "m": "preposition", "l": "ὑπό"},
                    {"h": "πάντων", "t": "pâs", "s": "G3956", "g": "all (manner of", "m": "adjective genitive plural masculine", "l": "πᾶς"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "ὑπὸ", "t": "hypó", "s": "G5259", "g": "among", "m": "preposition", "l": "ὑπό"},
                    {"h": "αὐτῆς", "t": "autós", "s": "G846", "g": "her", "m": "personal pronoun genitive singular feminine", "l": "αὐτός"},
                    {"h": "τῆς", "t": "ho", "s": "G3588", "g": "the", "m": "article genitive singular feminine", "l": "ὁ"},
                    {"h": "ἀληθείας", "t": "alḗtheia", "s": "G225", "g": "true", "m": "noun genitive singular feminine", "l": "ἀλήθεια"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "adverb", "l": "καί"},
                    {"h": "ἡμεῖς", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun nominative plural", "l": "ἐγώ"},
                    {"h": "δὲ", "t": "dé", "s": "G1161", "g": "also", "m": "conjunction", "l": "δέ"},
                    {"h": "μαρτυροῦμεν", "t": "martyréō", "s": "G3140", "g": "charge", "m": "verb 1st present active indicative plural", "l": "μαρτυρέω"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "⸀οἶδας", "m": "verb 2nd perfect active indicative singular", "l": "οἶδα"},
                    {"h": "ὅτι", "t": "hóti", "s": "G3754", "g": "as concerning that", "m": "conjunction"},
                    {"h": "ἡ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative singular feminine", "l": "ὁ"},
                    {"h": "μαρτυρία", "t": "martyría", "s": "G3141", "g": "record", "m": "noun nominative singular feminine"},
                    {"h": "ἡμῶν", "t": "egṓ", "s": "G1473", "g": "I", "m": "personal pronoun genitive plural", "l": "ἐγώ"},
                    {"h": "ἀληθής", "t": "alēthḗs", "s": "G227", "g": "true", "m": "adjective nominative singular feminine"},
                    {"h": "ἐστιν", "t": "eimí", "s": "G1510", "g": "am", "m": "verb 3rd present active indicative singular", "l": "εἰμί"},
                ]
            },
            {
                "num": 13,
                "words": [
                    {"h": "Πολλὰ", "t": "polýs", "s": "G4183", "g": "abundant", "m": "adjective accusative plural neuter", "l": "πολύς"},
                    {"h": "εἶχον", "t": "échō", "s": "G2192", "g": "be (able", "m": "verb 1st imperfect active indicative singular", "l": "ἔχω"},
                    {"h": "⸂γράψαι", "t": "gráphō", "s": "G1125", "g": "describe", "m": "verb aorist active infinitive", "l": "γράφω"},
                    {"h": "σοι⸃", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "ἀλλ’", "t": "allá", "s": "G235", "g": "and", "m": "conjunction", "l": "ἀλλά"},
                    {"h": "οὐ", "t": "ou", "s": "G3756", "g": "+ long", "m": "adverb"},
                    {"h": "θέλω", "t": "thélō", "s": "G2309", "g": "desire", "m": "verb 1st present active indicative singular"},
                    {"h": "διὰ", "t": "diá", "s": "G1223", "g": "after", "m": "preposition", "l": "διά"},
                    {"h": "μέλανος", "t": "mélan", "s": "G3188", "g": "ink", "m": "noun genitive singular neuter", "l": "μέλαν"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "καλάμου", "t": "kálamos", "s": "G2563", "g": "pen", "m": "noun genitive singular masculine", "l": "κάλαμος"},
                    {"h": "σοι", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "⸀γράφειν", "t": "gráphō", "s": "G1125", "g": "describe", "m": "verb present active infinitive", "l": "γράφω"},
                ]
            },
            {
                "num": 14,
                "words": [
                    {"h": "ἐλπίζω", "t": "elpízō", "s": "G1679", "g": "(have", "m": "verb 1st present active indicative singular"},
                    {"h": "δὲ", "t": "dé", "s": "G1161", "g": "also", "m": "conjunction", "l": "δέ"},
                    {"h": "εὐθέως", "t": "euthéōs", "s": "G2112", "g": "anon", "m": "adverb"},
                    {"h": "⸂σε", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun accusative singular", "l": "σύ"},
                    {"h": "ἰδεῖν⸃", "t": "horáō", "s": "G3708", "g": "behold", "m": "verb aorist active infinitive", "l": "ὁράω"},
                    {"h": "καὶ", "t": "kaí", "s": "G2532", "g": "and", "m": "conjunction", "l": "καί"},
                    {"h": "στόμα", "t": "stóma", "s": "G4750", "g": "edge", "m": "noun accusative singular neuter"},
                    {"h": "πρὸς", "t": "prós", "s": "G4314", "g": "about", "m": "preposition", "l": "πρός"},
                    {"h": "στόμα", "t": "stóma", "s": "G4750", "g": "edge", "m": "noun accusative singular neuter"},
                    {"h": "λαλήσομεν", "t": "laléō", "s": "G2980", "g": "preach", "m": "verb 1st future active indicative plural", "l": "λαλέω"},
                ]
            },
            {
                "num": 15,
                "words": [
                    {"h": "Εἰρήνη", "t": "eirḗnē", "s": "G1515", "g": "one", "m": "noun nominative singular feminine", "l": "εἰρήνη"},
                    {"h": "σοι", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun dative singular", "l": "σύ"},
                    {"h": "ἀσπάζονταί", "t": "aspázomai", "s": "G782", "g": "embrace", "m": "verb 3rd present middle indicative plural", "l": "ἀσπάζομαι"},
                    {"h": "σε", "t": "sý", "s": "G4771", "g": "thou", "m": "personal pronoun accusative singular", "l": "σύ"},
                    {"h": "οἱ", "t": "ho", "s": "G3588", "g": "the", "m": "article nominative plural masculine", "l": "ὁ"},
                    {"h": "φίλοι", "t": "phílos", "s": "G5384", "g": "friend", "m": "adjective nominative plural masculine", "l": "φίλος"},
                    {"h": "ἀσπάζου", "t": "aspázomai", "s": "G782", "g": "embrace", "m": "verb 2nd present middle imperative singular", "l": "ἀσπάζομαι"},
                    {"h": "τοὺς", "t": "ho", "s": "G3588", "g": "the", "m": "article accusative plural masculine", "l": "ὁ"},
                    {"h": "φίλους", "t": "phílos", "s": "G5384", "g": "friend", "m": "adjective accusative plural masculine", "l": "φίλος"},
                    {"h": "κατ’", "t": "katá", "s": "G2596", "g": "about", "m": "preposition", "l": "κατά"},
                    {"h": "ὄνομα", "t": "ónoma", "s": "G3686", "g": "called", "m": "noun accusative singular neuter"},
                ]
            },
        ]
    },
}
