"""
THE SCRIBE — Content Creation Agent

Generates new era data files, info.py intros, glossary entries,
and converts research material into structured study content.

Usage:
    python agents/scribe.py --task "Write DSS Community Rule era file"
    python agents/scribe.py --task-file agents/tasks/pending/task_001.json
"""
import os
import sys
import json
import argparse
from datetime import datetime

# Fix Windows console encoding for Unicode (Hebrew/Greek transliterations)
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from agents.config import (
    SCRIBE_API_KEY, SCRIBE_MODEL, SCRIBE_TEMPERATURE,
    DATA_DIR, MANIFEST_PATH, REPORTS_DIR, COMPLETED_DIR,
    THEOLOGICAL_GUIDELINES, ERA_DATA_FORMAT, MAX_TOKENS_SCRIBE
)


def get_client():
    """Create Anthropic client with SCRIBE's own API key."""
    if not SCRIBE_API_KEY:
        print("ERROR: Set SCRIBE_API_KEY in agents/config.py or environment")
        sys.exit(1)
    from anthropic import Anthropic
    return Anthropic(api_key=SCRIBE_API_KEY)


def load_example_era(text_id="genesis"):
    """Load an example era file as format reference."""
    # Find first available era file for the given text
    manifest = json.load(open(MANIFEST_PATH, "r", encoding="utf-8"))
    for era in manifest["eras"]:
        if era.get("text") == text_id and era.get("data_file"):
            data_dir = None
            for t in manifest["texts"]:
                if t["id"] == text_id:
                    data_dir = t.get("data_dir", text_id)
                    break
            if data_dir:
                path = os.path.join(DATA_DIR, data_dir, era["data_file"] + ".py")
                if not os.path.exists(path):
                    path = os.path.join(DATA_DIR, era["data_file"] + ".py")
                if os.path.exists(path):
                    with open(path, "r", encoding="utf-8") as f:
                        # Return first 200 lines as example
                        lines = f.readlines()[:200]
                        return "".join(lines)
    return "(No example era file found)"


def load_glossary_keys():
    """Load existing glossary term keys."""
    glossary_path = os.path.join(DATA_DIR, "glossary.py")
    if os.path.exists(glossary_path):
        import importlib.util
        spec = importlib.util.spec_from_file_location("glossary", glossary_path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return list(getattr(mod, "GLOSSARY", {}).keys())
    return []


def run_scribe(task_description, output_path=None):
    """Run THE SCRIBE to generate content."""
    client = get_client()

    example_era = load_example_era()
    glossary_keys = load_glossary_keys()

    system_prompt = f"""You are THE SCRIBE — a scholarly content creation agent for the Ancient Texts Study app.

Your role: Generate high-quality theological study content in Python data format.

{THEOLOGICAL_GUIDELINES}

{ERA_DATA_FORMAT}

EXISTING GLOSSARY TERMS (use these keys in hebrew_terms arrays):
{', '.join(glossary_keys[:100])}{'...' if len(glossary_keys) > 100 else ''}

EXAMPLE ERA FILE (first 200 lines):
```python
{example_era}
```

RULES:
1. Output ONLY valid Python code (a CHAPTERS list).
2. Every chapter must have all required fields.
3. Use existing glossary keys where possible.
4. Cross-references must include type: "ot", "nt", or "ane".
5. Divine council relevance must be explicitly stated.
6. HTML is allowed in section bodies and synopses.
7. Be thorough — each chapter should have 3-6 sections minimum.
8. Evidence tags [A], [B], [C] in synopses and section bodies.
"""

    print(f"\n{'='*60}")
    print(f"  THE SCRIBE — Content Generation")
    print(f"  Task: {task_description}")
    print(f"  Model: {SCRIBE_MODEL}")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'='*60}\n")

    response = client.messages.create(
        model=SCRIBE_MODEL,
        max_tokens=MAX_TOKENS_SCRIBE,
        temperature=SCRIBE_TEMPERATURE,
        system=system_prompt,
        messages=[
            {"role": "user", "content": task_description}
        ]
    )

    content = response.content[0].text

    # Extract Python code if wrapped in markdown
    if "```python" in content:
        content = content.split("```python")[1].split("```")[0]
    elif "```" in content:
        content = content.split("```")[1].split("```")[0]

    # Save output
    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f'"""\nGenerated by THE SCRIBE on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\nTask: {task_description}\n"""\n\n')
            f.write(content)
        print(f"[scribe] Output written to: {output_path}")

    # Log
    log_path = os.path.join(REPORTS_DIR, f"scribe_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log")
    os.makedirs(REPORTS_DIR, exist_ok=True)
    with open(log_path, "w", encoding="utf-8") as f:
        f.write(f"Task: {task_description}\n")
        f.write(f"Model: {SCRIBE_MODEL}\n")
        f.write(f"Tokens: {response.usage.input_tokens} in / {response.usage.output_tokens} out\n")
        f.write(f"Output: {output_path or '(stdout)'}\n")
        f.write(f"\n{'='*60}\n\n")
        f.write(content)
    print(f"[scribe] Log saved to: {log_path}")

    if not output_path:
        print(f"\n{'='*60}")
        print("GENERATED CONTENT:")
        print(f"{'='*60}\n")
        print(content)

    return content


def main():
    parser = argparse.ArgumentParser(description="THE SCRIBE — Content Creation Agent")
    parser.add_argument("--task", type=str, help="Task description")
    parser.add_argument("--task-file", type=str, help="Path to task JSON file")
    parser.add_argument("--output", type=str, help="Output file path")
    args = parser.parse_args()

    if args.task_file:
        with open(args.task_file, "r", encoding="utf-8") as f:
            task_data = json.load(f)
        task_desc = task_data.get("description", task_data.get("task", ""))
        output_path = task_data.get("output_path", args.output)
    elif args.task:
        task_desc = args.task
        output_path = args.output
    else:
        print("Usage: python agents/scribe.py --task 'Write era file for...'")
        sys.exit(1)

    run_scribe(task_desc, output_path)


if __name__ == "__main__":
    main()
